# Knowledge Distillation: 4-Layer Transformer — Alpha & Temperature Grid

This notebook runs 4-Layer-Standard transformer distillation for the same (alpha, temp) configs
that completed for Hybrid-CNN-3Layer, then produces the final comparison.

In [1]:
!pip install transformers datasets accelerate scikit-learn einops

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.3)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (0.8.2)

Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)

Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)

Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.3.5)

Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)

Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)

Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)

# Configuration & Imports

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random
import gc
import os
import json
import time
import sys
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    BertConfig,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    TrainerCallback,
)
from datasets import load_dataset
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# ===== Configurable Constants =====
TEACHER_NOTEBOOK_SLUG = "ml-project-kaggle15916a635e"
TEACHER_CHECKPOINT_PATH = f"/kaggle/input/{TEACHER_NOTEBOOK_SLUG}/lr_2e-05_results/checkpoint-4375"  # Best: 96.71%
TEACHER_FALLBACK_PATH = f"/kaggle/input/{TEACHER_NOTEBOOK_SLUG}/human_promoter_model"                # Fallback: 96.40%
MODEL_NAME = "quietflamingo/dnabert2-no-flashattention"
MAX_LENGTH = 300
BATCH_SIZE = 16
NUM_EPOCHS = 10
SEED = 42

# ===== Hyperparameter Grid =====
ALPHAS = [0.3, 0.5, 0.7]
TEMPERATURES = [1.0, 3.0, 5.0]

# ===== Reproducibility =====
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ===== GPU Info =====
device = "cuda" if torch.cuda.is_available() else "cpu"
num_gpus = torch.cuda.device_count()
print(f"Device: {device}")
print(f"Number of GPUs: {num_gpus}")
for i in range(num_gpus):
    name = torch.cuda.get_device_name(i)
    mem = torch.cuda.get_device_properties(i).total_memory / 1e9
    print(f"  GPU {i}: {name} ({mem:.1f} GB)")

print(f"\nHyperparameter grid: {len(ALPHAS)} alphas x {len(TEMPERATURES)} temps = {len(ALPHAS)*len(TEMPERATURES)} combos per architecture")
print(f"Alphas: {ALPHAS}")
print(f"Temperatures: {TEMPERATURES}")

Device: cuda
Number of GPUs: 2
  GPU 0: Tesla T4 (15.6 GB)
  GPU 1: Tesla T4 (15.6 GB)

Hyperparameter grid: 3 alphas x 3 temps = 9 combos per architecture
Alphas: [0.3, 0.5, 0.7]
Temperatures: [1.0, 3.0, 5.0]

# Load Dataset & Tokenize

In [3]:
# Load HUMAN promoter dataset from InstaDeepAI
print("Loading human promoter dataset from InstaDeepAI...")
raw_dataset = load_dataset("InstaDeepAI/nucleotide_transformer_downstream_tasks")

# Filter for promoter_all task only
def filter_promoter_all(example):
    return example["task"] == "promoter_all"

print("Filtering for promoter_all task...")
train_data_raw = raw_dataset["train"].filter(filter_promoter_all)
test_data_raw = raw_dataset["test"].filter(filter_promoter_all)

# Prepare data
def prepare_data(example):
    return {
        "sequence": example["sequence"].upper(),
        "label": int(example["label"]),
    }

train_data = train_data_raw.map(prepare_data)
test_data = test_data_raw.map(prepare_data)

print(f"Training samples: {len(train_data)}, Test samples: {len(test_data)}")

# Tokenize
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

def tokenize_func(examples):
    return tokenizer(examples["sequence"], padding="max_length", truncation=True, max_length=MAX_LENGTH)

print(f"Tokenizing with max_length={MAX_LENGTH}...")
tokenized_train = train_data.map(tokenize_func, batched=True)
tokenized_test = test_data.map(tokenize_func, batched=True)

# Set format for PyTorch and rename label -> labels for HuggingFace Trainer
tokenized_train.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
tokenized_test.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
tokenized_train = tokenized_train.rename_column("label", "labels")
tokenized_test = tokenized_test.rename_column("label", "labels")

train_dataset = tokenized_train
eval_dataset = tokenized_test

print(f"Tokenization complete!")
print(f"Train columns: {train_dataset.column_names}")
print(f"Sample input_ids shape: {train_dataset[0]['input_ids'].shape}")

Loading human promoter dataset from InstaDeepAI...

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

H3/train.parquet:   0%|          | 0.00/3.48M [00:00<?, ?B/s]

H3K9ac/train.parquet:   0%|          | 0.00/6.47M [00:00<?, ?B/s]

H3K14ac/train.parquet:   0%|          | 0.00/7.70M [00:00<?, ?B/s]

promoter_all/train.parquet:   0%|          | 0.00/8.41M [00:00<?, ?B/s]

enhancers_types/train.parquet:   0%|          | 0.00/1.47M [00:00<?, ?B/s]

enhancers/train.parquet:   0%|          | 0.00/1.47M [00:00<?, ?B/s]

H3K4me3/train.parquet:   0%|          | 0.00/8.58M [00:00<?, ?B/s]

H4/train.parquet:   0%|          | 0.00/3.39M [00:00<?, ?B/s]

H3K36me3/train.parquet:   0%|          | 0.00/8.13M [00:00<?, ?B/s]

promoter_tata/train.parquet:   0%|          | 0.00/867k [00:00<?, ?B/s]

H4ac/train.parquet:   0%|          | 0.00/7.94M [00:00<?, ?B/s]

H3K4me1/train.parquet:   0%|          | 0.00/7.38M [00:00<?, ?B/s]

H3K79me3/train.parquet:   0%|          | 0.00/6.72M [00:00<?, ?B/s]

H3K4me2/train.parquet:   0%|          | 0.00/7.15M [00:00<?, ?B/s]

promoter_no_tata/train.parquet:   0%|          | 0.00/7.53M [00:00<?, ?B/s]

splice_sites_acceptors/train.parquet:   0%|          | 0.00/5.90M [00:00<?, ?B/s]

splice_sites_donors/train.parquet:   0%|          | 0.00/5.85M [00:00<?, ?B/s]

splice_sites_all/train.parquet:   0%|          | 0.00/5.35M [00:00<?, ?B/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

H3K14ac/test.parquet:   0%|          | 0.00/859k [00:00<?, ?B/s]

H3/test.parquet:   0%|          | 0.00/389k [00:00<?, ?B/s]

H3K79me3/test.parquet:   0%|          | 0.00/748k [00:00<?, ?B/s]

enhancers_types/test.parquet:   0%|          | 0.00/41.2k [00:00<?, ?B/s]

H3K36me3/test.parquet:   0%|          | 0.00/905k [00:00<?, ?B/s]

promoter_all/test.parquet:   0%|          | 0.00/936k [00:00<?, ?B/s]

H3K4me3/test.parquet:   0%|          | 0.00/955k [00:00<?, ?B/s]

promoter_tata/test.parquet:   0%|          | 0.00/99.5k [00:00<?, ?B/s]

H4ac/test.parquet:   0%|          | 0.00/886k [00:00<?, ?B/s]

splice_sites_acceptors/test.parquet:   0%|          | 0.00/660k [00:00<?, ?B/s]

H3K9ac/test.parquet:   0%|          | 0.00/721k [00:00<?, ?B/s]

H4/test.parquet:   0%|          | 0.00/379k [00:00<?, ?B/s]

H3K4me2/test.parquet:   0%|          | 0.00/799k [00:00<?, ?B/s]

H3K4me1/test.parquet:   0%|          | 0.00/824k [00:00<?, ?B/s]

enhancers/test.parquet:   0%|          | 0.00/41.1k [00:00<?, ?B/s]

promoter_no_tata/test.parquet:   0%|          | 0.00/838k [00:00<?, ?B/s]

splice_sites_all/test.parquet:   0%|          | 0.00/594k [00:00<?, ?B/s]

splice_sites_donors/test.parquet:   0%|          | 0.00/655k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/461850 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/48797 [00:00<?, ? examples/s]

Filtering for promoter_all task...

Filter:   0%|          | 0/461850 [00:00<?, ? examples/s]

Filter:   0%|          | 0/48797 [00:00<?, ? examples/s]

Map:   0%|          | 0/53276 [00:00<?, ? examples/s]

Map:   0%|          | 0/5920 [00:00<?, ? examples/s]

Training samples: 53276, Test samples: 5920

config.json:   0%|          | 0.00/904 [00:00<?, ?B/s]

configuration_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/quietflamingo/dnabert2-no-flashattention:
- configuration_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

tokenizer_config.json:   0%|          | 0.00/158 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Tokenizing with max_length=300...

Map:   0%|          | 0/53276 [00:00<?, ? examples/s]

Map:   0%|          | 0/5920 [00:00<?, ? examples/s]

Tokenization complete!
Train columns: ['sequence', 'name', 'labels', 'task', 'input_ids', 'attention_mask']
Sample input_ids shape: torch.Size([300])

# Load Teacher Model

In [4]:
# Auto-discover teacher model path under /kaggle/input/
# Kaggle mounts notebook outputs at varying depths, e.g.:
#   /kaggle/input/notebooks/username/slug/lr_2e-05_results/checkpoint-4375/
import glob
from safetensors.torch import load_file as load_safetensors
from transformers import AutoConfig
from transformers.dynamic_module_utils import get_class_from_dynamic_module

def find_teacher_model():
    """Search all Kaggle inputs (recursively) for teacher checkpoint files."""
    base = "/kaggle/input"
    
    # Priority 1: Best checkpoint (96.71%)
    for filename in ["model.safetensors", "pytorch_model.bin"]:
        matches = glob.glob(f"{base}/**/lr_2e-05_results/checkpoint-4375/{filename}", recursive=True)
        if matches:
            return os.path.dirname(matches[0]), "best checkpoint (96.71%)"
    
    # Priority 2: Phase 1 model (96.40%)
    for filename in ["model.safetensors", "pytorch_model.bin"]:
        matches = glob.glob(f"{base}/**/human_promoter_model/{filename}", recursive=True)
        if matches:
            return os.path.dirname(matches[0]), "Phase 1 model (96.40%)"
    
    # Priority 3: Any checkpoint with config.json
    matches = glob.glob(f"{base}/**/human_promoter_results/checkpoint-*/config.json", recursive=True)
    if matches:
        return os.path.dirname(matches[0]), "fallback checkpoint"
    
    return None, None

teacher_path, teacher_desc = find_teacher_model()

if teacher_path is None:
    print("Contents of /kaggle/input/:")
    for root, dirs, files in os.walk("/kaggle/input"):
        depth = root.replace("/kaggle/input", "").count(os.sep)
        if depth < 3:
            indent = "  " * depth
            print(f"{indent}{os.path.basename(root)}/")
    raise FileNotFoundError(
        "Teacher model not found!\n"
        "Please add the teacher notebook output as a Kaggle input:\n"
        "  File -> Add Data -> Your Datasets -> Notebook Output"
    )

print(f"Found teacher: {teacher_desc}")
print(f"Path: {teacher_path}")

# Load config from hub and patch missing fields
config = AutoConfig.from_pretrained(MODEL_NAME, trust_remote_code=True)
config.num_labels = 2
config.pad_token_id = tokenizer.pad_token_id  # DNABERT-2 bert_layers.py:39 needs this

# Get DNABERT-2's custom model class from its auto_map
# (bypasses from_pretrained's meta-device context that breaks ALiBi tensor math)
class_ref = config.auto_map["AutoModelForSequenceClassification"]
model_class = get_class_from_dynamic_module(class_ref, MODEL_NAME)

# Direct instantiation on CPU — no meta device wrapping
teacher_model = model_class(config)

# Load fine-tuned checkpoint weights
weights_file = os.path.join(teacher_path, "model.safetensors")
if os.path.exists(weights_file):
    state_dict = load_safetensors(weights_file)
else:
    weights_file = os.path.join(teacher_path, "pytorch_model.bin")
    state_dict = torch.load(weights_file, map_location="cpu", weights_only=True)

teacher_model.load_state_dict(state_dict)
print(f"Loaded fine-tuned weights from: {os.path.basename(weights_file)}")

teacher_model.eval()

teacher_params = sum(p.numel() for p in teacher_model.parameters())
print(f"Teacher model loaded successfully!")
print(f"Teacher parameters: {teacher_params:,} ({teacher_params/1e6:.1f}M)")

Found teacher: best checkpoint (96.71%)
Path: /kaggle/input/notebooks/sheikhrahatmahmud/ml-project-kaggle15916a635e/lr_2e-05_results/checkpoint-4375

bert_layers.py: 0.00B [00:00, ?B/s]

bert_padding.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/quietflamingo/dnabert2-no-flashattention:
- bert_padding.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

A new version of the following files was downloaded from https://huggingface.co/quietflamingo/dnabert2-no-flashattention:
- bert_layers.py
- bert_padding.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

/root/.cache/huggingface/modules/transformers_modules/quietflamingo/dnabert2_hyphen_no_hyphen_flashattention/813031b2bf86d9e960a027e2734c908009f31601/bert_layers.py:123: UserWarning: Unable to import Triton; defaulting MosaicBERT attention implementation to pytorch (this will reduce throughput when using this model).
  warnings.warn(

Loaded fine-tuned weights from: model.safetensors
Teacher model loaded successfully!
Teacher parameters: 117,070,082 (117.1M)

# Distillation Trainer & Student Architectures

In [5]:
from transformers.modeling_outputs import SequenceClassifierOutput

# ===== DISTILLATION TRAINER =====
class DistillationTrainer(Trainer):
    def __init__(self, *args, teacher_model=None, alpha=0.5, temperature=3.0, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher_model = teacher_model.to(self.args.device)
        self.alpha = alpha
        self.temperature = temperature
        self.teacher_model.eval()

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Student predictions
        outputs_student = model(**inputs)
        student_logits = outputs_student.logits
        labels = inputs.get("labels")

        # Teacher predictions (no gradients needed)
        with torch.no_grad():
            outputs_teacher = self.teacher_model(**inputs)
            teacher_logits = outputs_teacher.logits

        # Soft Loss: Matching the Teacher's probability distribution
        soft_loss = nn.KLDivLoss(reduction="batchmean")(
            F.log_softmax(student_logits / self.temperature, dim=-1),
            F.softmax(teacher_logits / self.temperature, dim=-1)
        ) * (self.temperature ** 2)

        # Hard Loss: Correctness against ground truth
        hard_loss = F.cross_entropy(student_logits, labels)

        # Final balanced loss
        loss = self.alpha * hard_loss + (1 - self.alpha) * soft_loss

        return (loss, outputs_student) if return_outputs else loss


# ===== HYBRID CNN-TRANSFORMER STUDENT =====
class DNAHybridStudent(nn.Module):
    def __init__(self, layers=2):
        super().__init__()
        # 1. Very small Transformer backbone
        config = BertConfig.from_pretrained("quietflamingo/dnabert2-no-flashattention", num_hidden_layers=layers)
        self.bert = BertForSequenceClassification(config).bert
        
        # 2. CNN Head for Motif Scanning
        self.conv = nn.Conv1d(in_channels=768, out_channels=128, kernel_size=9, padding=4)
        self.pool = nn.AdaptiveMaxPool1d(1)
        self.classifier = nn.Linear(128, 2)

    def forward(self, input_ids, attention_mask=None, labels=None):
        # Transformer pass
        outputs = self.bert(input_ids, attention_mask=attention_mask)
        sequence_output = outputs.last_hidden_state  # [batch, seq_len, 768]
        
        # CNN pass (permute to [batch, 768, seq_len])
        x = sequence_output.permute(0, 2, 1)
        x = torch.relu(self.conv(x))
        x = self.pool(x).squeeze(-1)
        
        logits = self.classifier(x)
        
        loss = None
        if labels is not None:
            loss = nn.CrossEntropyLoss()(logits, labels)
            
        return SequenceClassifierOutput(loss=loss, logits=logits)


# ===== HELPER: PURE TRANSFORMER STUDENT =====
def get_pure_transformer(layers):
    config = BertConfig.from_pretrained(
        "quietflamingo/dnabert2-no-flashattention",
        num_hidden_layers=layers, num_labels=2,
    )
    return BertForSequenceClassification(config)


# ===== COMPUTE METRICS =====
def compute_metrics(pred):
    labels = pred.label_ids
    logits = pred.predictions[0] if isinstance(pred.predictions, tuple) else pred.predictions
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall": recall_score(labels, preds),
    }


# ===== PROGRESS CALLBACK =====
class ProgressCallback(TrainerCallback):
    """Custom callback to force print output in Kaggle"""
    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            print(f"Step {state.global_step}: {logs}", flush=True)

    def on_epoch_begin(self, args, state, control, **kwargs):
        print(f"\n{'='*60}", flush=True)
        print(f"Starting Epoch {int(state.epoch) + 1}/{args.num_train_epochs}", flush=True)
        print(f"{'='*60}", flush=True)

    def on_epoch_end(self, args, state, control, **kwargs):
        print(f"Epoch {int(state.epoch)} completed!", flush=True)


# ===== PARAMETER COUNTING =====
def count_parameters(model):
    return sum(p.numel() for p in model.parameters())


print("All components defined successfully!")

All components defined successfully!

# Run Grid Search: 2 Architectures x Alpha x Temperature

In [6]:
# ===== PREVIOUSLY COMPLETED RESULTS (Hybrid-CNN-3Layer from first run) =====
final_results = {
    "Hybrid-CNN-3Layer_a0.3_t1.0": {
        "architecture": "Hybrid-CNN-3Layer", "alpha": 0.3, "temperature": 1.0,
        "accuracy": 0.9282, "f1": 0.9273, "precision": 0.9393, "recall": 0.9155,
        "loss": 0.1052, "params": 26281346, "compression": 4.454, "train_time_min": 154.2
    },
    "Hybrid-CNN-3Layer_a0.3_t3.0": {
        "architecture": "Hybrid-CNN-3Layer", "alpha": 0.3, "temperature": 3.0,
        "accuracy": 0.9331, "f1": 0.9326, "precision": 0.9402, "recall": 0.9250,
        "loss": 0.1195, "params": 26281346, "compression": 4.454, "train_time_min": 154.3
    },
    "Hybrid-CNN-3Layer_a0.3_t5.0": {
        "architecture": "Hybrid-CNN-3Layer", "alpha": 0.3, "temperature": 5.0,
        "accuracy": 0.9309, "f1": 0.9302, "precision": 0.9400, "recall": 0.9206,
        "loss": 0.1226, "params": 26281346, "compression": 4.454, "train_time_min": 154.3
    },
    "Hybrid-CNN-3Layer_a0.5_t1.0": {
        "architecture": "Hybrid-CNN-3Layer", "alpha": 0.5, "temperature": 1.0,
        "accuracy": 0.9274, "f1": 0.9258, "precision": 0.9461, "recall": 0.9064,
        "loss": 0.1392, "params": 26281346, "compression": 4.454, "train_time_min": 154.1
    },
}

print(f"Loaded {len(final_results)} completed Hybrid-CNN-3Layer results:")
for key, res in final_results.items():
    print(f"  {key}: {res['accuracy']:.2%}")

# ===== MODEL SIZE COMPARISON =====
teacher_params = count_parameters(teacher_model)

print("="*70)
print("MODEL SIZE COMPARISON")
print("="*70)
print(f"{'Model':<25} {'Parameters':>15} {'Layers':>8} {'Compression':>12}")
print("-"*70)
print(f"{'Teacher (DNABERT-2)':<25} {teacher_params:>15,} {'12':>8} {'1.0x':>12}")

_preview_4l = get_pure_transformer(4)
_p4 = count_parameters(_preview_4l)
print(f"{'4-Layer-Standard':<25} {_p4:>15,} {'4':>8} {teacher_params/_p4:>11.1f}x")

_preview_hybrid = DNAHybridStudent(layers=3)
_ph = count_parameters(_preview_hybrid)
print(f"{'Hybrid-CNN-3Layer':<25} {_ph:>15,} {'3+CNN':>8} {teacher_params/_ph:>11.1f}x")
print("="*70)
del _preview_4l, _preview_hybrid
gc.collect()

# ===== RUNS: 4-Layer-Standard for same (alpha, temp) as completed Hybrid =====
runs_to_do = [
    ("4-Layer-Standard", 0.3, 1.0),
    ("4-Layer-Standard", 0.3, 3.0),
    ("4-Layer-Standard", 0.3, 5.0),
    ("4-Layer-Standard", 0.5, 1.0),
]

print(f"\nRuns to complete: {len(runs_to_do)} (4-Layer-Standard)")
print(f"Estimated time: ~{len(runs_to_do) * 154 / 60:.1f} hours")

for run_i, (arch_name, alpha, temperature) in enumerate(runs_to_do):
    run_key = f"{arch_name}_a{alpha}_t{temperature}"

    print(f"\n{'#'*70}")
    print(f"# Run {run_i+1}/{len(runs_to_do)}: {arch_name} | alpha={alpha} | temp={temperature}")
    print(f"{'#'*70}")

    gc.collect()
    torch.cuda.empty_cache()

    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(SEED)

    student_model = get_pure_transformer(4)
    student_params = count_parameters(student_model)
    print(f"Student parameters: {student_params:,} ({student_params/1e6:.1f}M)")

    args = TrainingArguments(
        output_dir=f"/kaggle/working/{run_key}",
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        fp16=True,
        logging_steps=100,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_accuracy",
        greater_is_better=True,
        save_total_limit=1,
        report_to="none",
        remove_unused_columns=True,
        warmup_ratio=0.1,
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        learning_rate=2e-5,
    )

    start_time = time.time()

    trainer = DistillationTrainer(
        model=student_model,
        teacher_model=teacher_model,
        alpha=alpha,
        temperature=temperature,
        args=args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        compute_metrics=compute_metrics,
        callbacks=[
            EarlyStoppingCallback(early_stopping_patience=3),
            ProgressCallback(),
        ],
    )

    print(f"\nStarting training...", flush=True)
    trainer.train()
    train_time = time.time() - start_time

    metrics = trainer.evaluate()
    print(f"\n--- {run_key} Results ---")
    print(f"  Accuracy:  {metrics['eval_accuracy']:.2%}")
    print(f"  F1 Score:  {metrics['eval_f1']:.4f}")
    print(f"  Precision: {metrics['eval_precision']:.4f}")
    print(f"  Recall:    {metrics['eval_recall']:.4f}")
    print(f"  Loss:      {metrics['eval_loss']:.4f}")
    print(f"  Time:      {train_time/60:.1f} min")

    save_dir = f"/kaggle/working/{run_key}_final"
    os.makedirs(save_dir, exist_ok=True)
    student_model.save_pretrained(save_dir)

    final_results[run_key] = {
        "architecture": arch_name,
        "alpha": alpha,
        "temperature": temperature,
        "accuracy": metrics["eval_accuracy"],
        "f1": metrics["eval_f1"],
        "precision": metrics["eval_precision"],
        "recall": metrics["eval_recall"],
        "loss": metrics["eval_loss"],
        "params": student_params,
        "compression": teacher_params / student_params,
        "train_time_min": round(train_time / 60, 1),
    }

    # Save after each run (safe against timeout)
    with open("/kaggle/working/partial_results.json", "w") as f:
        json.dump(final_results, f, indent=2)
    print(f"  Results saved ({len(final_results)} total)")

    del trainer, student_model
    gc.collect()
    torch.cuda.empty_cache()

print(f"\nAll {len(runs_to_do)} runs completed!")
print(f"Total results: {len(final_results)} (4 Hybrid + 4 Transformer)")

Loaded 4 completed Hybrid-CNN-3Layer results:
  Hybrid-CNN-3Layer_a0.3_t1.0: 92.82%
  Hybrid-CNN-3Layer_a0.3_t3.0: 93.31%
  Hybrid-CNN-3Layer_a0.3_t5.0: 93.09%
  Hybrid-CNN-3Layer_a0.5_t1.0: 92.74%
======================================================================
MODEL SIZE COMPARISON
======================================================================
Model                          Parameters   Layers  Compression
----------------------------------------------------------------------
Teacher (DNABERT-2)           117,070,082       12         1.0x

4-Layer-Standard               32,485,634        4         3.6x

Hybrid-CNN-3Layer              26,281,346    3+CNN         4.5x
======================================================================

Runs to complete: 4 (4-Layer-Standard)
Estimated time: ~10.3 hours

######################################################################
# Run 1/4: 4-Layer-Standard | alpha=0.3 | temp=1.0
######################################################################

Student parameters: 32,485,634 (32.5M)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting training...

============================================================

Starting Epoch 1/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 100: {'loss': 0.5103741836547852, 'grad_norm': 2.962489128112793, 'learning_rate': 1.1891891891891893e-06, 'epoch': 0.06006006006006006}

Step 200: {'loss': 0.49391998291015626, 'grad_norm': 4.267110824584961, 'learning_rate': 2.3903903903903904e-06, 'epoch': 0.12012012012012012}

Step 300: {'loss': 0.4881278610229492, 'grad_norm': 1.9261945486068726, 'learning_rate': 3.5915915915915917e-06, 'epoch': 0.18018018018018017}

Step 400: {'loss': 0.48280982971191405, 'grad_norm': 4.48767614364624, 'learning_rate': 4.792792792792793e-06, 'epoch': 0.24024024024024024}

Step 500: {'loss': 0.47510921478271484, 'grad_norm': 3.90680193901062, 'learning_rate': 5.993993993993994e-06, 'epoch': 0.3003003003003003}

Step 600: {'loss': 0.44543609619140623, 'grad_norm': 11.426986694335938, 'learning_rate': 7.195195195195196e-06, 'epoch': 0.36036036036036034}

Step 700: {'loss': 0.33932712554931643, 'grad_norm': 2.485222816467285, 'learning_rate': 8.396396396396397e-06, 'epoch': 0.42042042042042044}

Step 800: {'loss': 0.27003002166748047, 'grad_norm': 15.552942276000977, 'learning_rate': 9.597597597597599e-06, 'epoch': 0.4804804804804805}

Step 900: {'loss': 0.27389886856079104, 'grad_norm': 6.445322036743164, 'learning_rate': 1.07987987987988e-05, 'epoch': 0.5405405405405406}

Step 1000: {'loss': 0.25177684783935544, 'grad_norm': 17.042644500732422, 'learning_rate': 1.2e-05, 'epoch': 0.6006006006006006}

Step 1100: {'loss': 0.25180004119873045, 'grad_norm': 23.262496948242188, 'learning_rate': 1.3201201201201202e-05, 'epoch': 0.6606606606606606}

Step 1200: {'loss': 0.26774513244628906, 'grad_norm': 22.61725616455078, 'learning_rate': 1.4402402402402404e-05, 'epoch': 0.7207207207207207}

Step 1300: {'loss': 0.22390920639038087, 'grad_norm': 5.1708760261535645, 'learning_rate': 1.5603603603603605e-05, 'epoch': 0.7807807807807807}

Step 1400: {'loss': 0.22733606338500978, 'grad_norm': 25.47295379638672, 'learning_rate': 1.6804804804804807e-05, 'epoch': 0.8408408408408409}

Step 1500: {'loss': 0.25089136123657224, 'grad_norm': 6.297815799713135, 'learning_rate': 1.8006006006006005e-05, 'epoch': 0.9009009009009009}

Step 1600: {'loss': 0.2088899803161621, 'grad_norm': 15.857460021972656, 'learning_rate': 1.9207207207207207e-05, 'epoch': 0.960960960960961}

Epoch 1 completed!

Step 1665: {'eval_loss': 0.17873230576515198, 'eval_accuracy': 0.8677364864864865, 'eval_f1': 0.8693475721675288, 'eval_precision': 0.8588855918232773, 'eval_recall': 0.8800675675675675, 'eval_runtime': 74.2767, 'eval_samples_per_second': 79.702, 'eval_steps_per_second': 2.491, 'epoch': 1.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 2/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 1700: {'loss': 0.1982777786254883, 'grad_norm': 1.8078423738479614, 'learning_rate': 1.9999745954064855e-05, 'epoch': 1.021021021021021}

Step 1800: {'loss': 0.21204809188842774, 'grad_norm': 2.098649024963379, 'learning_rate': 1.9996054179825038e-05, 'epoch': 1.0810810810810811}

Step 1900: {'loss': 0.20542821884155274, 'grad_norm': 7.509979248046875, 'learning_rate': 1.998796902380012e-05, 'epoch': 1.1411411411411412}

Step 2000: {'loss': 0.2042258071899414, 'grad_norm': 24.31817054748535, 'learning_rate': 1.997549403950997e-05, 'epoch': 1.2012012012012012}

Step 2100: {'loss': 0.18729124069213868, 'grad_norm': 26.027610778808594, 'learning_rate': 1.995863470985492e-05, 'epoch': 1.2612612612612613}

Step 2200: {'loss': 0.20113645553588866, 'grad_norm': 7.282939910888672, 'learning_rate': 1.9937398444705953e-05, 'epoch': 1.3213213213213213}

Step 2300: {'loss': 0.19075677871704103, 'grad_norm': 9.201849937438965, 'learning_rate': 1.991179457764798e-05, 'epoch': 1.3813813813813813}

Step 2400: {'loss': 0.18744489669799805, 'grad_norm': 19.751628875732422, 'learning_rate': 1.988183436187763e-05, 'epoch': 1.4414414414414414}

Step 2500: {'loss': 0.1976000213623047, 'grad_norm': 13.331476211547852, 'learning_rate': 1.9847530965257328e-05, 'epoch': 1.5015015015015014}

Step 2600: {'loss': 0.17929847717285155, 'grad_norm': 2.906217098236084, 'learning_rate': 1.9808899464527874e-05, 'epoch': 1.5615615615615615}

Step 2700: {'loss': 0.16781349182128907, 'grad_norm': 13.441750526428223, 'learning_rate': 1.9765956838682032e-05, 'epoch': 1.6216216216216215}

Step 2800: {'loss': 0.18115118026733398, 'grad_norm': 12.962295532226562, 'learning_rate': 1.971872196150208e-05, 'epoch': 1.6816816816816815}

Step 2900: {'loss': 0.19436244964599608, 'grad_norm': 25.030353546142578, 'learning_rate': 1.9667215593264558e-05, 'epoch': 1.7417417417417418}

Step 3000: {'loss': 0.20259029388427735, 'grad_norm': 24.98602294921875, 'learning_rate': 1.9611460371615865e-05, 'epoch': 1.8018018018018018}

Step 3100: {'loss': 0.1828024673461914, 'grad_norm': 5.636370658874512, 'learning_rate': 1.955148080162279e-05, 'epoch': 1.8618618618618619}

Step 3200: {'loss': 0.17458677291870117, 'grad_norm': 21.048547744750977, 'learning_rate': 1.9487303245002217e-05, 'epoch': 1.921921921921922}

Step 3300: {'loss': 0.18259008407592772, 'grad_norm': 23.371747970581055, 'learning_rate': 1.9418955908534863e-05, 'epoch': 1.981981981981982}

Epoch 2 completed!

Step 3330: {'eval_loss': 0.17163151502609253, 'eval_accuracy': 0.88125, 'eval_f1': 0.8854489164086687, 'eval_precision': 0.8552093169656909, 'eval_recall': 0.9179054054054054, 'eval_runtime': 74.3408, 'eval_samples_per_second': 79.633, 'eval_steps_per_second': 2.489, 'epoch': 2.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 3/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 3400: {'loss': 0.18209999084472656, 'grad_norm': 32.51953887939453, 'learning_rate': 1.9346468831668065e-05, 'epoch': 2.042042042042042}

Step 3500: {'loss': 0.15713807106018066, 'grad_norm': 2.665724992752075, 'learning_rate': 1.926987387331309e-05, 'epoch': 2.1021021021021022}

Step 3600: {'loss': 0.1540674877166748, 'grad_norm': 19.050878524780273, 'learning_rate': 1.918920469784278e-05, 'epoch': 2.1621621621621623}

Step 3700: {'loss': 0.14950862884521485, 'grad_norm': 5.340656757354736, 'learning_rate': 1.9104496760295675e-05, 'epoch': 2.2222222222222223}

Step 3800: {'loss': 0.16661197662353516, 'grad_norm': 16.713977813720703, 'learning_rate': 1.9015787290793092e-05, 'epoch': 2.2822822822822824}

Step 3900: {'loss': 0.15008266448974608, 'grad_norm': 13.46291446685791, 'learning_rate': 1.892311527817608e-05, 'epoch': 2.3423423423423424}

Step 4000: {'loss': 0.16144342422485353, 'grad_norm': 9.264839172363281, 'learning_rate': 1.8826521452869348e-05, 'epoch': 2.4024024024024024}

Step 4100: {'loss': 0.16907072067260742, 'grad_norm': 9.003283500671387, 'learning_rate': 1.872604826897979e-05, 'epoch': 2.4624624624624625}

Step 4200: {'loss': 0.15459138870239258, 'grad_norm': 11.852663040161133, 'learning_rate': 1.8621739885637407e-05, 'epoch': 2.5225225225225225}

Step 4300: {'loss': 0.16080883026123047, 'grad_norm': 34.41373062133789, 'learning_rate': 1.8513642147586855e-05, 'epoch': 2.5825825825825826}

Step 4400: {'loss': 0.17128080368041992, 'grad_norm': 12.937628746032715, 'learning_rate': 1.8401802565038135e-05, 'epoch': 2.6426426426426426}

Step 4500: {'loss': 0.15372047424316407, 'grad_norm': 4.8264265060424805, 'learning_rate': 1.8286270292785337e-05, 'epoch': 2.7027027027027026}

Step 4600: {'loss': 0.15206185340881348, 'grad_norm': 14.166984558105469, 'learning_rate': 1.81670961086025e-05, 'epoch': 2.7627627627627627}

Step 4700: {'loss': 0.16577503204345703, 'grad_norm': 36.907737731933594, 'learning_rate': 1.8044332390926224e-05, 'epoch': 2.8228228228228227}

Step 4800: {'loss': 0.1715225601196289, 'grad_norm': 2.2221434116363525, 'learning_rate': 1.7918033095834714e-05, 'epoch': 2.8828828828828827}

Step 4900: {'loss': 0.15934508323669433, 'grad_norm': 4.293479919433594, 'learning_rate': 1.778825373333347e-05, 'epoch': 2.942942942942943}

Epoch 3 completed!

Step 4995: {'eval_loss': 0.2403881549835205, 'eval_accuracy': 0.831418918918919, 'eval_f1': 0.800877893056664, 'eval_precision': 0.9780701754385965, 'eval_recall': 0.6780405405405405, 'eval_runtime': 74.5949, 'eval_samples_per_second': 79.362, 'eval_steps_per_second': 2.48, 'epoch': 3.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 4/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 5000: {'loss': 0.14950017929077147, 'grad_norm': 10.424538612365723, 'learning_rate': 1.7655051342958005e-05, 'epoch': 3.003003003003003}

Step 5100: {'loss': 0.14153303146362306, 'grad_norm': 9.553513526916504, 'learning_rate': 1.7518484468704283e-05, 'epoch': 3.063063063063063}

Step 5200: {'loss': 0.14476177215576172, 'grad_norm': 2.165351390838623, 'learning_rate': 1.7378613133297974e-05, 'epoch': 3.123123123123123}

Step 5300: {'loss': 0.14304155349731446, 'grad_norm': 4.388733386993408, 'learning_rate': 1.7235498811813757e-05, 'epoch': 3.1831831831831834}

Step 5400: {'loss': 0.14259855270385743, 'grad_norm': 1.688481330871582, 'learning_rate': 1.708920440465632e-05, 'epoch': 3.2432432432432434}

Step 5500: {'loss': 0.14736955642700195, 'grad_norm': 16.049800872802734, 'learning_rate': 1.6939794209914907e-05, 'epoch': 3.3033033033033035}

Step 5600: {'loss': 0.13556750297546385, 'grad_norm': 9.052562713623047, 'learning_rate': 1.6787333895103535e-05, 'epoch': 3.3633633633633635}

Step 5700: {'loss': 0.13444998741149902, 'grad_norm': 3.795386791229248, 'learning_rate': 1.6631890468299402e-05, 'epoch': 3.4234234234234235}

Step 5800: {'loss': 0.13827855110168458, 'grad_norm': 8.783807754516602, 'learning_rate': 1.6473532248692016e-05, 'epoch': 3.4834834834834836}

Step 5900: {'loss': 0.1334070682525635, 'grad_norm': 20.965606689453125, 'learning_rate': 1.6312328836556152e-05, 'epoch': 3.5435435435435436}

Step 6000: {'loss': 0.13597531318664552, 'grad_norm': 3.4480838775634766, 'learning_rate': 1.6148351082661707e-05, 'epoch': 3.6036036036036037}

Step 6100: {'loss': 0.1426732921600342, 'grad_norm': 3.007373332977295, 'learning_rate': 1.5981671057133975e-05, 'epoch': 3.6636636636636637}

Step 6200: {'loss': 0.13153260231018066, 'grad_norm': 13.062878608703613, 'learning_rate': 1.5812362017777965e-05, 'epoch': 3.7237237237237237}

Step 6300: {'loss': 0.13319830894470214, 'grad_norm': 8.975449562072754, 'learning_rate': 1.564049837788079e-05, 'epoch': 3.7837837837837838}

Step 6400: {'loss': 0.12709511756896974, 'grad_norm': 7.98157262802124, 'learning_rate': 1.546615567350612e-05, 'epoch': 3.843843843843844}

Step 6500: {'loss': 0.13081339836120606, 'grad_norm': 25.51782989501953, 'learning_rate': 1.5289410530295233e-05, 'epoch': 3.903903903903904}

Step 6600: {'loss': 0.11983968734741211, 'grad_norm': 4.359918594360352, 'learning_rate': 1.5110340629789148e-05, 'epoch': 3.963963963963964}

Epoch 4 completed!

Step 6660: {'eval_loss': 0.15723136067390442, 'eval_accuracy': 0.8927364864864865, 'eval_f1': 0.8835503392627911, 'eval_precision': 0.9663056558363418, 'eval_recall': 0.8138513513513513, 'eval_runtime': 74.3058, 'eval_samples_per_second': 79.671, 'eval_steps_per_second': 2.49, 'epoch': 4.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 5/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 6700: {'loss': 0.12724736213684082, 'grad_norm': 2.926691770553589, 'learning_rate': 1.4929024675286688e-05, 'epoch': 4.024024024024024}

Step 6800: {'loss': 0.11992424964904785, 'grad_norm': 6.496248245239258, 'learning_rate': 1.4745542357253462e-05, 'epoch': 4.084084084084084}

Step 6900: {'loss': 0.11339801788330078, 'grad_norm': 10.875399589538574, 'learning_rate': 1.4559974318296984e-05, 'epoch': 4.1441441441441444}

Step 7000: {'loss': 0.12118752479553223, 'grad_norm': 4.9230451583862305, 'learning_rate': 1.4372402117723314e-05, 'epoch': 4.2042042042042045}

Step 7100: {'loss': 0.11443202972412109, 'grad_norm': 7.938194274902344, 'learning_rate': 1.4182908195690799e-05, 'epoch': 4.2642642642642645}

Step 7200: {'loss': 0.1114277744293213, 'grad_norm': 4.8048996925354, 'learning_rate': 1.399157583697666e-05, 'epoch': 4.324324324324325}

Step 7300: {'loss': 0.11387423515319824, 'grad_norm': 14.599699974060059, 'learning_rate': 1.3798489134372361e-05, 'epoch': 4.384384384384385}

Step 7400: {'loss': 0.11252077102661133, 'grad_norm': 6.460547924041748, 'learning_rate': 1.3603732951723874e-05, 'epoch': 4.444444444444445}

Step 7500: {'loss': 0.10676695823669434, 'grad_norm': 3.359604597091675, 'learning_rate': 1.3407392886633008e-05, 'epoch': 4.504504504504505}

Step 7600: {'loss': 0.10898870468139649, 'grad_norm': 3.6095998287200928, 'learning_rate': 1.3209555232836284e-05, 'epoch': 4.564564564564565}

Step 7700: {'loss': 0.1051981258392334, 'grad_norm': 14.457355499267578, 'learning_rate': 1.301030694227784e-05, 'epoch': 4.624624624624625}

Step 7800: {'loss': 0.111275053024292, 'grad_norm': 6.28779411315918, 'learning_rate': 1.2809735586893028e-05, 'epoch': 4.684684684684685}

Step 7900: {'loss': 0.1068675708770752, 'grad_norm': 1.800446629524231, 'learning_rate': 1.2607929320119547e-05, 'epoch': 4.744744744744745}

Step 8000: {'loss': 0.10895519256591797, 'grad_norm': 5.611281871795654, 'learning_rate': 1.2404976838152977e-05, 'epoch': 4.804804804804805}

Step 8100: {'loss': 0.10637785911560059, 'grad_norm': 7.163759708404541, 'learning_rate': 1.2200967340963774e-05, 'epoch': 4.864864864864865}

Step 8200: {'loss': 0.09901577949523926, 'grad_norm': 1.6639994382858276, 'learning_rate': 1.1995990493092849e-05, 'epoch': 4.924924924924925}

Step 8300: {'loss': 0.10850850105285645, 'grad_norm': 2.6837918758392334, 'learning_rate': 1.1790136384242957e-05, 'epoch': 4.984984984984985}

Epoch 5 completed!

Step 8325: {'eval_loss': 0.11832094192504883, 'eval_accuracy': 0.9195945945945946, 'eval_f1': 0.9164619164619164, 'eval_precision': 0.9536157779401022, 'eval_recall': 0.8820945945945946, 'eval_runtime': 74.2712, 'eval_samples_per_second': 79.708, 'eval_steps_per_second': 2.491, 'epoch': 5.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 6/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 8400: {'loss': 0.09852207183837891, 'grad_norm': 24.94349479675293, 'learning_rate': 1.158349548968323e-05, 'epoch': 5.045045045045045}

Step 8500: {'loss': 0.0906926441192627, 'grad_norm': 9.980391502380371, 'learning_rate': 1.1376158630484258e-05, 'epoch': 5.105105105105105}

Step 8600: {'loss': 0.08890582084655761, 'grad_norm': 22.255416870117188, 'learning_rate': 1.116821693360115e-05, 'epoch': 5.165165165165165}

Step 8700: {'loss': 0.10579972267150879, 'grad_norm': 1.5400230884552002, 'learning_rate': 1.0959761791822208e-05, 'epoch': 5.225225225225225}

Step 8800: {'loss': 0.0957914924621582, 'grad_norm': 3.3410964012145996, 'learning_rate': 1.0750884823600713e-05, 'epoch': 5.285285285285285}

Step 8900: {'loss': 0.09868523597717285, 'grad_norm': 4.129462242126465, 'learning_rate': 1.0541677832787569e-05, 'epoch': 5.345345345345345}

Step 9000: {'loss': 0.09904746055603027, 'grad_norm': 11.242650985717773, 'learning_rate': 1.0332232768282429e-05, 'epoch': 5.405405405405405}

Step 9100: {'loss': 0.09093008995056152, 'grad_norm': 3.94480299949646, 'learning_rate': 1.0122641683621102e-05, 'epoch': 5.465465465465465}

Step 9200: {'loss': 0.09876502990722656, 'grad_norm': 11.622179985046387, 'learning_rate': 9.912996696516946e-06, 'epoch': 5.525525525525525}

Step 9300: {'loss': 0.09424569129943848, 'grad_norm': 1.9903717041015625, 'learning_rate': 9.703389948374077e-06, 'epoch': 5.585585585585585}

Step 9400: {'loss': 0.09804224967956543, 'grad_norm': 4.080440998077393, 'learning_rate': 9.493913563790135e-06, 'epoch': 5.645645645645645}

Step 9500: {'loss': 0.09192395210266113, 'grad_norm': 10.439909934997559, 'learning_rate': 9.28465961006646e-06, 'epoch': 5.7057057057057055}

Step 9600: {'loss': 0.09509841918945312, 'grad_norm': 5.849312782287598, 'learning_rate': 9.07572005674346e-06, 'epoch': 5.7657657657657655}

Step 9700: {'loss': 0.09103818893432618, 'grad_norm': 3.992537498474121, 'learning_rate': 8.867186735178911e-06, 'epoch': 5.8258258258258255}

Step 9800: {'loss': 0.0869229793548584, 'grad_norm': 3.1992361545562744, 'learning_rate': 8.659151298187018e-06, 'epoch': 5.885885885885886}

Step 9900: {'loss': 0.09697270393371582, 'grad_norm': 5.703420639038086, 'learning_rate': 8.451705179755947e-06, 'epoch': 5.945945945945946}

Epoch 6 completed!

Step 9990: {'eval_loss': 0.11007526516914368, 'eval_accuracy': 0.9222972972972973, 'eval_f1': 0.9228187919463087, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.9290540540540541, 'eval_runtime': 74.4653, 'eval_samples_per_second': 79.5, 'eval_steps_per_second': 2.484, 'epoch': 6.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 7/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 10000: {'loss': 0.09353169441223144, 'grad_norm': 12.005882263183594, 'learning_rate': 8.244939554861512e-06, 'epoch': 6.006006006006006}

Step 10100: {'loss': 0.08321154594421387, 'grad_norm': 7.685886859893799, 'learning_rate': 8.038945299394722e-06, 'epoch': 6.066066066066066}

Step 10200: {'loss': 0.08446500778198242, 'grad_norm': 8.317399024963379, 'learning_rate': 7.833812950220783e-06, 'epoch': 6.126126126126126}

Step 10300: {'loss': 0.08490007400512695, 'grad_norm': 1.740083932876587, 'learning_rate': 7.62963266538707e-06, 'epoch': 6.186186186186186}

Step 10400: {'loss': 0.08602020263671875, 'grad_norm': 4.668725490570068, 'learning_rate': 7.426494184497655e-06, 'epoch': 6.246246246246246}

Step 10500: {'loss': 0.08786439895629883, 'grad_norm': 1.4495595693588257, 'learning_rate': 7.224486789271671e-06, 'epoch': 6.306306306306306}

Step 10600: {'loss': 0.08479166030883789, 'grad_norm': 3.352478265762329, 'learning_rate': 7.0236992643029854e-06, 'epoch': 6.366366366366367}

Step 10700: {'loss': 0.08034398078918457, 'grad_norm': 5.263920783996582, 'learning_rate': 6.824219858038339e-06, 'epoch': 6.426426426426427}

Step 10800: {'loss': 0.08184703826904297, 'grad_norm': 5.749393463134766, 'learning_rate': 6.626136243991124e-06, 'epoch': 6.486486486486487}

Step 10900: {'loss': 0.08357502937316895, 'grad_norm': 6.897630214691162, 'learning_rate': 6.429535482207847e-06, 'epoch': 6.546546546546547}

Step 11000: {'loss': 0.08301334381103516, 'grad_norm': 13.658214569091797, 'learning_rate': 6.234503981004265e-06, 'epoch': 6.606606606606607}

Step 11100: {'loss': 0.08815298080444336, 'grad_norm': 2.235814094543457, 'learning_rate': 6.0411274589878834e-06, 'epoch': 6.666666666666667}

Step 11200: {'loss': 0.08638628959655761, 'grad_norm': 4.38097620010376, 'learning_rate': 5.849490907383659e-06, 'epoch': 6.726726726726727}

Step 11300: {'loss': 0.08502077102661133, 'grad_norm': 10.154664039611816, 'learning_rate': 5.659678552679371e-06, 'epoch': 6.786786786786787}

Step 11400: {'loss': 0.0824827480316162, 'grad_norm': 2.61425518989563, 'learning_rate': 5.471773819607095e-06, 'epoch': 6.846846846846847}

Step 11500: {'loss': 0.08089293479919434, 'grad_norm': 2.820302963256836, 'learning_rate': 5.285859294477054e-06, 'epoch': 6.906906906906907}

Step 11600: {'loss': 0.08432780265808106, 'grad_norm': 1.5592825412750244, 'learning_rate': 5.102016688880014e-06, 'epoch': 6.966966966966967}

Epoch 7 completed!

Step 11655: {'eval_loss': 0.1296187788248062, 'eval_accuracy': 0.9131756756756757, 'eval_f1': 0.9075206908960057, 'eval_precision': 0.970746728252502, 'eval_recall': 0.852027027027027, 'eval_runtime': 74.1554, 'eval_samples_per_second': 79.832, 'eval_steps_per_second': 2.495, 'epoch': 7.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 8/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 11700: {'loss': 0.07907827377319336, 'grad_norm': 11.293140411376953, 'learning_rate': 4.920326803774047e-06, 'epoch': 7.027027027027027}

Step 11800: {'loss': 0.07630550384521484, 'grad_norm': 5.370368957519531, 'learning_rate': 4.7408694939716095e-06, 'epoch': 7.087087087087087}

Step 11900: {'loss': 0.07635582447052001, 'grad_norm': 7.274546146392822, 'learning_rate': 4.5637236330424005e-06, 'epoch': 7.147147147147147}

Step 12000: {'loss': 0.08460002899169922, 'grad_norm': 3.692553997039795, 'learning_rate': 4.3889670786475195e-06, 'epoch': 7.207207207207207}

Step 12100: {'loss': 0.0761163330078125, 'grad_norm': 10.367080688476562, 'learning_rate': 4.216676638320135e-06, 'epoch': 7.267267267267267}

Step 12200: {'loss': 0.08093218803405762, 'grad_norm': 4.284596920013428, 'learning_rate': 4.0469280357076625e-06, 'epoch': 7.327327327327327}

Step 12300: {'loss': 0.07940587520599365, 'grad_norm': 9.609819412231445, 'learning_rate': 3.879795877290354e-06, 'epoch': 7.387387387387387}

Step 12400: {'loss': 0.0787765121459961, 'grad_norm': 7.023657321929932, 'learning_rate': 3.7153536195908813e-06, 'epoch': 7.4474474474474475}

Step 12500: {'loss': 0.07555788516998291, 'grad_norm': 2.7309410572052, 'learning_rate': 3.5536735368893436e-06, 'epoch': 7.5075075075075075}

Step 12600: {'loss': 0.078896803855896, 'grad_norm': 7.10822057723999, 'learning_rate': 3.3948266894578796e-06, 'epoch': 7.5675675675675675}

Step 12700: {'loss': 0.07526161193847657, 'grad_norm': 8.858983993530273, 'learning_rate': 3.238882892328864e-06, 'epoch': 7.627627627627628}

Step 12800: {'loss': 0.07717791557312012, 'grad_norm': 8.074766159057617, 'learning_rate': 3.085910684610374e-06, 'epoch': 7.687687687687688}

Step 12900: {'loss': 0.07725589752197265, 'grad_norm': 5.354421138763428, 'learning_rate': 2.9359772993624635e-06, 'epoch': 7.747747747747748}

Step 13000: {'loss': 0.07340717315673828, 'grad_norm': 1.6586353778839111, 'learning_rate': 2.7891486340474683e-06, 'epoch': 7.807807807807808}

Step 13100: {'loss': 0.07635118961334228, 'grad_norm': 1.9315311908721924, 'learning_rate': 2.6454892215672767e-06, 'epoch': 7.867867867867868}

Step 13200: {'loss': 0.07966259479522705, 'grad_norm': 14.886273384094238, 'learning_rate': 2.5050622019003934e-06, 'epoch': 7.927927927927928}

Step 13300: {'loss': 0.07669615268707275, 'grad_norm': 2.071549415588379, 'learning_rate': 2.3679292943511858e-06, 'epoch': 7.987987987987988}

Epoch 8 completed!

Step 13320: {'eval_loss': 0.11482913047075272, 'eval_accuracy': 0.9226351351351352, 'eval_f1': 0.9190812720848056, 'eval_precision': 0.9633333333333334, 'eval_recall': 0.8787162162162162, 'eval_runtime': 74.2239, 'eval_samples_per_second': 79.759, 'eval_steps_per_second': 2.492, 'epoch': 8.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 9/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 13400: {'loss': 0.07353049755096436, 'grad_norm': 9.704133033752441, 'learning_rate': 2.234150770423518e-06, 'epoch': 8.048048048048049}

Step 13500: {'loss': 0.07211225032806397, 'grad_norm': 2.562185287475586, 'learning_rate': 2.103785427330739e-06, 'epoch': 8.108108108108109}

Step 13600: {'loss': 0.06953718185424805, 'grad_norm': 2.4490835666656494, 'learning_rate': 1.976890562153623e-06, 'epoch': 8.168168168168169}

Step 13700: {'loss': 0.07925465106964111, 'grad_norm': 3.2636702060699463, 'learning_rate': 1.8535219466576327e-06, 'epoch': 8.228228228228229}

Step 13800: {'loss': 0.07168828487396241, 'grad_norm': 9.294390678405762, 'learning_rate': 1.7337338027805907e-06, 'epoch': 8.288288288288289}

Step 13900: {'loss': 0.0755616044998169, 'grad_norm': 4.944295883178711, 'learning_rate': 1.6175787788014974e-06, 'epoch': 8.348348348348349}

Step 14000: {'loss': 0.07330981731414794, 'grad_norm': 1.0499162673950195, 'learning_rate': 1.505107926201007e-06, 'epoch': 8.408408408408409}

Step 14100: {'loss': 0.0762189769744873, 'grad_norm': 4.352090358734131, 'learning_rate': 1.3963706772237161e-06, 'epoch': 8.468468468468469}

Step 14200: {'loss': 0.06870262622833252, 'grad_norm': 5.2920708656311035, 'learning_rate': 1.291414823152104e-06, 'epoch': 8.528528528528529}

Step 14300: {'loss': 0.06906242370605468, 'grad_norm': 3.664997100830078, 'learning_rate': 1.19028649330172e-06, 'epoch': 8.588588588588589}

Step 14400: {'loss': 0.07292343616485596, 'grad_norm': 14.575551986694336, 'learning_rate': 1.0930301347468154e-06, 'epoch': 8.64864864864865}

Step 14500: {'loss': 0.07426793575286865, 'grad_norm': 12.73948860168457, 'learning_rate': 9.996884927853312e-07, 'epoch': 8.70870870870871}

Step 14600: {'loss': 0.072058744430542, 'grad_norm': 4.448102951049805, 'learning_rate': 9.103025921518482e-07, 'epoch': 8.76876876876877}

Step 14700: {'loss': 0.06970251083374024, 'grad_norm': 7.3349199295043945, 'learning_rate': 8.249117189867395e-07, 'epoch': 8.82882882882883}

Step 14800: {'loss': 0.07458682537078858, 'grad_norm': 3.656808614730835, 'learning_rate': 7.435534035694548e-07, 'epoch': 8.88888888888889}

Step 14900: {'loss': 0.07243201732635499, 'grad_norm': 4.827848434448242, 'learning_rate': 6.662634038235328e-07, 'epoch': 8.94894894894895}

Epoch 9 completed!

Step 14985: {'eval_loss': 0.10970704257488251, 'eval_accuracy': 0.925168918918919, 'eval_f1': 0.9227550130775938, 'eval_precision': 0.9535135135135135, 'eval_recall': 0.893918918918919, 'eval_runtime': 74.4739, 'eval_samples_per_second': 79.491, 'eval_steps_per_second': 2.484, 'epoch': 9.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 10/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 15000: {'loss': 0.07346144676208496, 'grad_norm': 2.239439010620117, 'learning_rate': 5.930756896005707e-07, 'epoch': 9.00900900900901}

Step 15100: {'loss': 0.07110475540161133, 'grad_norm': 2.7640488147735596, 'learning_rate': 5.240224277500827e-07, 'epoch': 9.06906906906907}

Step 15200: {'loss': 0.07007446765899658, 'grad_norm': 3.618413209915161, 'learning_rate': 4.591339679818041e-07, 'epoch': 9.12912912912913}

Step 15300: {'loss': 0.06739888191223145, 'grad_norm': 3.045942783355713, 'learning_rate': 3.984388295266284e-07, 'epoch': 9.18918918918919}

Step 15400: {'loss': 0.07597751140594483, 'grad_norm': 7.536161422729492, 'learning_rate': 3.4196368860208495e-07, 'epoch': 9.24924924924925}

Step 15500: {'loss': 0.06974557399749756, 'grad_norm': 4.832370281219482, 'learning_rate': 2.897333666878299e-07, 'epoch': 9.30930930930931}

Step 15600: {'loss': 0.0733591890335083, 'grad_norm': 1.6258867979049683, 'learning_rate': 2.4177081961631264e-07, 'epoch': 9.36936936936937}

Step 15700: {'loss': 0.07469779491424561, 'grad_norm': 5.0779266357421875, 'learning_rate': 1.980971274834287e-07, 'epoch': 9.42942942942943}

Step 15800: {'loss': 0.07061965942382813, 'grad_norm': 1.151253342628479, 'learning_rate': 1.5873148538356752e-07, 'epoch': 9.48948948948949}

Step 15900: {'loss': 0.07352795600891113, 'grad_norm': 3.8948538303375244, 'learning_rate': 1.2369119497314674e-07, 'epoch': 9.54954954954955}

Step 16000: {'loss': 0.06900109767913819, 'grad_norm': 5.97643518447876, 'learning_rate': 9.299165686633471e-08, 'epoch': 9.60960960960961}

Step 16100: {'loss': 0.07061273574829102, 'grad_norm': 4.364600658416748, 'learning_rate': 6.664636386630286e-08, 'epoch': 9.66966966966967}

Step 16200: {'loss': 0.07170129776000976, 'grad_norm': 5.796435832977295, 'learning_rate': 4.466689503498045e-08, 'epoch': 9.72972972972973}

Step 16300: {'loss': 0.06304132461547851, 'grad_norm': 4.338729381561279, 'learning_rate': 2.7062910603921078e-08, 'epoch': 9.78978978978979}

Step 16400: {'loss': 0.07247308254241944, 'grad_norm': 6.488291263580322, 'learning_rate': 1.3842147728522215e-08, 'epoch': 9.84984984984985}

Step 16500: {'loss': 0.06802440643310546, 'grad_norm': 3.424410820007324, 'learning_rate': 5.010417087452091e-09, 'epoch': 9.90990990990991}

Step 16600: {'loss': 0.07030353546142579, 'grad_norm': 1.7540173530578613, 'learning_rate': 5.716003287936645e-10, 'epoch': 9.96996996996997}

Epoch 10 completed!

Step 16650: {'eval_loss': 0.10848013311624527, 'eval_accuracy': 0.9260135135135135, 'eval_f1': 0.9238790406673618, 'eval_precision': 0.9513242662848962, 'eval_recall': 0.897972972972973, 'eval_runtime': 74.2542, 'eval_samples_per_second': 79.726, 'eval_steps_per_second': 2.491, 'epoch': 10.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 16650: {'train_runtime': 10758.2791, 'train_samples_per_second': 49.521, 'train_steps_per_second': 1.548, 'total_flos': 2.7757476441072e+16, 'train_loss': 0.1333837784661187, 'epoch': 10.0}

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 16650: {'eval_loss': 0.10848013311624527, 'eval_accuracy': 0.9260135135135135, 'eval_f1': 0.9238790406673618, 'eval_precision': 0.9513242662848962, 'eval_recall': 0.897972972972973, 'eval_runtime': 74.1495, 'eval_samples_per_second': 79.839, 'eval_steps_per_second': 2.495, 'epoch': 10.0}

--- 4-Layer-Standard_a0.3_t1.0 Results ---
  Accuracy:  92.60%
  F1 Score:  0.9239
  Precision: 0.9513
  Recall:    0.8980
  Loss:      0.1085
  Time:      179.3 min

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Results saved (5 total)

######################################################################
# Run 2/4: 4-Layer-Standard | alpha=0.3 | temp=3.0
######################################################################

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Student parameters: 32,485,634 (32.5M)

Starting training...

============================================================

Starting Epoch 1/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 100: {'loss': 0.8120266723632813, 'grad_norm': 3.684112071990967, 'learning_rate': 1.1891891891891893e-06, 'epoch': 0.06006006006006006}

Step 200: {'loss': 0.7812734985351563, 'grad_norm': 5.143180847167969, 'learning_rate': 2.3903903903903904e-06, 'epoch': 0.12012012012012012}

Step 300: {'loss': 0.7719084167480469, 'grad_norm': 2.1837263107299805, 'learning_rate': 3.5915915915915917e-06, 'epoch': 0.18018018018018017}

Step 400: {'loss': 0.7648654174804688, 'grad_norm': 4.660629749298096, 'learning_rate': 4.792792792792793e-06, 'epoch': 0.24024024024024024}

Step 500: {'loss': 0.7501620483398438, 'grad_norm': 8.841996192932129, 'learning_rate': 5.993993993993994e-06, 'epoch': 0.3003003003003003}

Step 600: {'loss': 0.6531340789794922, 'grad_norm': 26.551198959350586, 'learning_rate': 7.195195195195196e-06, 'epoch': 0.36036036036036034}

Step 700: {'loss': 0.4909325408935547, 'grad_norm': 38.84519577026367, 'learning_rate': 8.396396396396397e-06, 'epoch': 0.42042042042042044}

Step 800: {'loss': 0.404453125, 'grad_norm': 16.966251373291016, 'learning_rate': 9.597597597597599e-06, 'epoch': 0.4804804804804805}

Step 900: {'loss': 0.3691828536987305, 'grad_norm': 30.63898277282715, 'learning_rate': 1.07987987987988e-05, 'epoch': 0.5405405405405406}

Step 1000: {'loss': 0.35063770294189456, 'grad_norm': 43.66133117675781, 'learning_rate': 1.2e-05, 'epoch': 0.6006006006006006}

Step 1100: {'loss': 0.3415254211425781, 'grad_norm': 43.8869743347168, 'learning_rate': 1.3201201201201202e-05, 'epoch': 0.6606606606606606}

Step 1200: {'loss': 0.3550830841064453, 'grad_norm': 29.683107376098633, 'learning_rate': 1.4402402402402404e-05, 'epoch': 0.7207207207207207}

Step 1300: {'loss': 0.3690272521972656, 'grad_norm': 10.063336372375488, 'learning_rate': 1.5603603603603605e-05, 'epoch': 0.7807807807807807}

Step 1400: {'loss': 0.3165586471557617, 'grad_norm': 11.184426307678223, 'learning_rate': 1.6804804804804807e-05, 'epoch': 0.8408408408408409}

Step 1500: {'loss': 0.30633092880249024, 'grad_norm': 12.941259384155273, 'learning_rate': 1.8006006006006005e-05, 'epoch': 0.9009009009009009}

Step 1600: {'loss': 0.3238509750366211, 'grad_norm': 35.799835205078125, 'learning_rate': 1.9207207207207207e-05, 'epoch': 0.960960960960961}

Epoch 1 completed!

Step 1665: {'eval_loss': 0.29191285371780396, 'eval_accuracy': 0.835472972972973, 'eval_f1': 0.8507050889025138, 'eval_precision': 0.7786195286195287, 'eval_recall': 0.9375, 'eval_runtime': 74.0833, 'eval_samples_per_second': 79.91, 'eval_steps_per_second': 2.497, 'epoch': 1.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 2/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 1700: {'loss': 0.2819566917419434, 'grad_norm': 24.00745964050293, 'learning_rate': 1.9999745954064855e-05, 'epoch': 1.021021021021021}

Step 1800: {'loss': 0.26484495162963867, 'grad_norm': 22.057876586914062, 'learning_rate': 1.9996054179825038e-05, 'epoch': 1.0810810810810811}

Step 1900: {'loss': 0.27946857452392576, 'grad_norm': 31.50205421447754, 'learning_rate': 1.998796902380012e-05, 'epoch': 1.1411411411411412}

Step 2000: {'loss': 0.3095273971557617, 'grad_norm': 61.828041076660156, 'learning_rate': 1.997549403950997e-05, 'epoch': 1.2012012012012012}

Step 2100: {'loss': 0.26522724151611327, 'grad_norm': 19.763574600219727, 'learning_rate': 1.995863470985492e-05, 'epoch': 1.2612612612612613}

Step 2200: {'loss': 0.23739376068115234, 'grad_norm': 4.636109828948975, 'learning_rate': 1.9937398444705953e-05, 'epoch': 1.3213213213213213}

Step 2300: {'loss': 0.2436540412902832, 'grad_norm': 4.495538711547852, 'learning_rate': 1.991179457764798e-05, 'epoch': 1.3813813813813813}

Step 2400: {'loss': 0.2472176170349121, 'grad_norm': 4.751539707183838, 'learning_rate': 1.988183436187763e-05, 'epoch': 1.4414414414414414}

Step 2500: {'loss': 0.25546960830688475, 'grad_norm': 21.467166900634766, 'learning_rate': 1.9847530965257328e-05, 'epoch': 1.5015015015015014}

Step 2600: {'loss': 0.24945140838623048, 'grad_norm': 14.932711601257324, 'learning_rate': 1.9808899464527874e-05, 'epoch': 1.5615615615615615}

Step 2700: {'loss': 0.25342782974243167, 'grad_norm': 14.317283630371094, 'learning_rate': 1.9765956838682032e-05, 'epoch': 1.6216216216216215}

Step 2800: {'loss': 0.23366275787353516, 'grad_norm': 12.089076042175293, 'learning_rate': 1.971872196150208e-05, 'epoch': 1.6816816816816815}

Step 2900: {'loss': 0.24173357009887694, 'grad_norm': 32.51960372924805, 'learning_rate': 1.9667215593264558e-05, 'epoch': 1.7417417417417418}

Step 3000: {'loss': 0.27472724914550783, 'grad_norm': 19.29154396057129, 'learning_rate': 1.9611460371615865e-05, 'epoch': 1.8018018018018018}

Step 3100: {'loss': 0.22477535247802735, 'grad_norm': 2.3846688270568848, 'learning_rate': 1.955148080162279e-05, 'epoch': 1.8618618618618619}

Step 3200: {'loss': 0.2606709671020508, 'grad_norm': 18.586715698242188, 'learning_rate': 1.9487303245002217e-05, 'epoch': 1.921921921921922}

Step 3300: {'loss': 0.2333171272277832, 'grad_norm': 28.046422958374023, 'learning_rate': 1.9418955908534863e-05, 'epoch': 1.981981981981982}

Epoch 2 completed!

Step 3330: {'eval_loss': 0.2216712385416031, 'eval_accuracy': 0.8770270270270271, 'eval_f1': 0.8821243523316062, 'eval_precision': 0.8470149253731343, 'eval_recall': 0.9202702702702703, 'eval_runtime': 74.2534, 'eval_samples_per_second': 79.727, 'eval_steps_per_second': 2.491, 'epoch': 2.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 3/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 3400: {'loss': 0.24001041412353516, 'grad_norm': 54.0301399230957, 'learning_rate': 1.9346468831668065e-05, 'epoch': 2.042042042042042}

Step 3500: {'loss': 0.22093902587890624, 'grad_norm': 13.161128044128418, 'learning_rate': 1.926987387331309e-05, 'epoch': 2.1021021021021022}

Step 3600: {'loss': 0.20595394134521483, 'grad_norm': 36.10356903076172, 'learning_rate': 1.918920469784278e-05, 'epoch': 2.1621621621621623}

Step 3700: {'loss': 0.20509597778320313, 'grad_norm': 18.562328338623047, 'learning_rate': 1.9104496760295675e-05, 'epoch': 2.2222222222222223}

Step 3800: {'loss': 0.2227486801147461, 'grad_norm': 39.43863296508789, 'learning_rate': 1.9015787290793092e-05, 'epoch': 2.2822822822822824}

Step 3900: {'loss': 0.20960556030273436, 'grad_norm': 28.158702850341797, 'learning_rate': 1.892311527817608e-05, 'epoch': 2.3423423423423424}

Step 4000: {'loss': 0.20395984649658203, 'grad_norm': 25.475154876708984, 'learning_rate': 1.8826521452869348e-05, 'epoch': 2.4024024024024024}

Step 4100: {'loss': 0.2101728630065918, 'grad_norm': 32.01236343383789, 'learning_rate': 1.872604826897979e-05, 'epoch': 2.4624624624624625}

Step 4200: {'loss': 0.20470882415771485, 'grad_norm': 10.64053726196289, 'learning_rate': 1.8621739885637407e-05, 'epoch': 2.5225225225225225}

Step 4300: {'loss': 0.2100127601623535, 'grad_norm': 28.22370147705078, 'learning_rate': 1.8513642147586855e-05, 'epoch': 2.5825825825825826}

Step 4400: {'loss': 0.20600849151611328, 'grad_norm': 19.95254898071289, 'learning_rate': 1.8401802565038135e-05, 'epoch': 2.6426426426426426}

Step 4500: {'loss': 0.19485061645507812, 'grad_norm': 4.14435338973999, 'learning_rate': 1.8286270292785337e-05, 'epoch': 2.7027027027027026}

Step 4600: {'loss': 0.18979610443115236, 'grad_norm': 22.0367374420166, 'learning_rate': 1.81670961086025e-05, 'epoch': 2.7627627627627627}

Step 4700: {'loss': 0.2039793014526367, 'grad_norm': 13.799567222595215, 'learning_rate': 1.8044332390926224e-05, 'epoch': 2.8228228228228227}

Step 4800: {'loss': 0.2235561752319336, 'grad_norm': 18.2921142578125, 'learning_rate': 1.7918033095834714e-05, 'epoch': 2.8828828828828827}

Step 4900: {'loss': 0.19957229614257813, 'grad_norm': 9.468149185180664, 'learning_rate': 1.778825373333347e-05, 'epoch': 2.942942942942943}

Epoch 3 completed!

Step 4995: {'eval_loss': 0.18396350741386414, 'eval_accuracy': 0.8994932432432432, 'eval_f1': 0.899272050110039, 'eval_precision': 0.9012555140821175, 'eval_recall': 0.8972972972972973, 'eval_runtime': 74.1581, 'eval_samples_per_second': 79.829, 'eval_steps_per_second': 2.495, 'epoch': 3.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 4/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 5000: {'loss': 0.19898456573486328, 'grad_norm': 8.1865234375, 'learning_rate': 1.7655051342958005e-05, 'epoch': 3.003003003003003}

Step 5100: {'loss': 0.18049945831298828, 'grad_norm': 4.560125350952148, 'learning_rate': 1.7518484468704283e-05, 'epoch': 3.063063063063063}

Step 5200: {'loss': 0.18616212844848634, 'grad_norm': 10.705004692077637, 'learning_rate': 1.7378613133297974e-05, 'epoch': 3.123123123123123}

Step 5300: {'loss': 0.18217479705810546, 'grad_norm': 5.185220718383789, 'learning_rate': 1.7235498811813757e-05, 'epoch': 3.1831831831831834}

Step 5400: {'loss': 0.17914276123046874, 'grad_norm': 11.57243537902832, 'learning_rate': 1.708920440465632e-05, 'epoch': 3.2432432432432434}

Step 5500: {'loss': 0.1783272361755371, 'grad_norm': 10.2891206741333, 'learning_rate': 1.6939794209914907e-05, 'epoch': 3.3033033033033035}

Step 5600: {'loss': 0.16459739685058594, 'grad_norm': 17.784021377563477, 'learning_rate': 1.6787333895103535e-05, 'epoch': 3.3633633633633635}

Step 5700: {'loss': 0.1589967918395996, 'grad_norm': 9.039950370788574, 'learning_rate': 1.6631890468299402e-05, 'epoch': 3.4234234234234235}

Step 5800: {'loss': 0.16170576095581055, 'grad_norm': 17.23558235168457, 'learning_rate': 1.6473532248692016e-05, 'epoch': 3.4834834834834836}

Step 5900: {'loss': 0.1683504104614258, 'grad_norm': 32.470706939697266, 'learning_rate': 1.6312328836556152e-05, 'epoch': 3.5435435435435436}

Step 6000: {'loss': 0.1473434543609619, 'grad_norm': 3.6012020111083984, 'learning_rate': 1.6148351082661707e-05, 'epoch': 3.6036036036036037}

Step 6100: {'loss': 0.1569483184814453, 'grad_norm': 8.606904029846191, 'learning_rate': 1.5981671057133975e-05, 'epoch': 3.6636636636636637}

Step 6200: {'loss': 0.15115424156188964, 'grad_norm': 14.57235336303711, 'learning_rate': 1.5812362017777965e-05, 'epoch': 3.7237237237237237}

Step 6300: {'loss': 0.14303272247314452, 'grad_norm': 4.4375433921813965, 'learning_rate': 1.564049837788079e-05, 'epoch': 3.7837837837837838}

Step 6400: {'loss': 0.13897056579589845, 'grad_norm': 7.505908012390137, 'learning_rate': 1.546615567350612e-05, 'epoch': 3.843843843843844}

Step 6500: {'loss': 0.14334830284118652, 'grad_norm': 7.768454074859619, 'learning_rate': 1.5289410530295233e-05, 'epoch': 3.903903903903904}

Step 6600: {'loss': 0.13257147789001464, 'grad_norm': 8.433364868164062, 'learning_rate': 1.5110340629789148e-05, 'epoch': 3.963963963963964}

Epoch 4 completed!

Step 6660: {'eval_loss': 0.14546333253383636, 'eval_accuracy': 0.9162162162162162, 'eval_f1': 0.9149228130360206, 'eval_precision': 0.9292682926829269, 'eval_recall': 0.9010135135135136, 'eval_runtime': 74.5166, 'eval_samples_per_second': 79.445, 'eval_steps_per_second': 2.483, 'epoch': 4.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 5/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 6700: {'loss': 0.1392704200744629, 'grad_norm': 7.537234306335449, 'learning_rate': 1.4929024675286688e-05, 'epoch': 4.024024024024024}

Step 6800: {'loss': 0.128058500289917, 'grad_norm': 3.3792881965637207, 'learning_rate': 1.4745542357253462e-05, 'epoch': 4.084084084084084}

Step 6900: {'loss': 0.1294808006286621, 'grad_norm': 5.463397026062012, 'learning_rate': 1.4559974318296984e-05, 'epoch': 4.1441441441441444}

Step 7000: {'loss': 0.13163077354431152, 'grad_norm': 5.432211399078369, 'learning_rate': 1.4372402117723314e-05, 'epoch': 4.2042042042042045}

Step 7100: {'loss': 0.1313464069366455, 'grad_norm': 7.259994029998779, 'learning_rate': 1.4182908195690799e-05, 'epoch': 4.2642642642642645}

Step 7200: {'loss': 0.121697359085083, 'grad_norm': 2.130358934402466, 'learning_rate': 1.399157583697666e-05, 'epoch': 4.324324324324325}

Step 7300: {'loss': 0.13145228385925292, 'grad_norm': 8.990880966186523, 'learning_rate': 1.3798489134372361e-05, 'epoch': 4.384384384384385}

Step 7400: {'loss': 0.12922335624694825, 'grad_norm': 5.98421573638916, 'learning_rate': 1.3603732951723874e-05, 'epoch': 4.444444444444445}

Step 7500: {'loss': 0.11752337455749512, 'grad_norm': 4.845414638519287, 'learning_rate': 1.3407392886633008e-05, 'epoch': 4.504504504504505}

Step 7600: {'loss': 0.13091330528259276, 'grad_norm': 3.9899795055389404, 'learning_rate': 1.3209555232836284e-05, 'epoch': 4.564564564564565}

Step 7700: {'loss': 0.12775302886962892, 'grad_norm': 17.216062545776367, 'learning_rate': 1.301030694227784e-05, 'epoch': 4.624624624624625}

Step 7800: {'loss': 0.12199630737304687, 'grad_norm': 15.950976371765137, 'learning_rate': 1.2809735586893028e-05, 'epoch': 4.684684684684685}

Step 7900: {'loss': 0.12134977340698243, 'grad_norm': 3.1577272415161133, 'learning_rate': 1.2607929320119547e-05, 'epoch': 4.744744744744745}

Step 8000: {'loss': 0.1303729820251465, 'grad_norm': 18.83612823486328, 'learning_rate': 1.2404976838152977e-05, 'epoch': 4.804804804804805}

Step 8100: {'loss': 0.1296073341369629, 'grad_norm': 6.8667311668396, 'learning_rate': 1.2200967340963774e-05, 'epoch': 4.864864864864865}

Step 8200: {'loss': 0.11864582061767578, 'grad_norm': 4.041779518127441, 'learning_rate': 1.1995990493092849e-05, 'epoch': 4.924924924924925}

Step 8300: {'loss': 0.13083566665649415, 'grad_norm': 4.725767612457275, 'learning_rate': 1.1790136384242957e-05, 'epoch': 4.984984984984985}

Epoch 5 completed!

Step 8325: {'eval_loss': 0.1330418735742569, 'eval_accuracy': 0.9239864864864865, 'eval_f1': 0.9219021173203749, 'eval_precision': 0.9478943611705924, 'eval_recall': 0.8972972972972973, 'eval_runtime': 74.3688, 'eval_samples_per_second': 79.603, 'eval_steps_per_second': 2.488, 'epoch': 5.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 6/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 8400: {'loss': 0.10725876808166504, 'grad_norm': 5.034364223480225, 'learning_rate': 1.158349548968323e-05, 'epoch': 5.045045045045045}

Step 8500: {'loss': 0.10354650497436524, 'grad_norm': 6.387156009674072, 'learning_rate': 1.1376158630484258e-05, 'epoch': 5.105105105105105}

Step 8600: {'loss': 0.10942629814147949, 'grad_norm': 28.294546127319336, 'learning_rate': 1.116821693360115e-05, 'epoch': 5.165165165165165}

Step 8700: {'loss': 0.11720677375793458, 'grad_norm': 1.0571523904800415, 'learning_rate': 1.0959761791822208e-05, 'epoch': 5.225225225225225}

Step 8800: {'loss': 0.11079967498779297, 'grad_norm': 10.709242820739746, 'learning_rate': 1.0750884823600713e-05, 'epoch': 5.285285285285285}

Step 8900: {'loss': 0.11722752571105957, 'grad_norm': 3.8525094985961914, 'learning_rate': 1.0541677832787569e-05, 'epoch': 5.345345345345345}

Step 9000: {'loss': 0.11775970458984375, 'grad_norm': 8.08129596710205, 'learning_rate': 1.0332232768282429e-05, 'epoch': 5.405405405405405}

Step 9100: {'loss': 0.11098573684692382, 'grad_norm': 1.590813159942627, 'learning_rate': 1.0122641683621102e-05, 'epoch': 5.465465465465465}

Step 9200: {'loss': 0.11010702133178711, 'grad_norm': 6.57621955871582, 'learning_rate': 9.912996696516946e-06, 'epoch': 5.525525525525525}

Step 9300: {'loss': 0.11401642799377441, 'grad_norm': 4.452815055847168, 'learning_rate': 9.703389948374077e-06, 'epoch': 5.585585585585585}

Step 9400: {'loss': 0.11542377471923829, 'grad_norm': 10.162009239196777, 'learning_rate': 9.493913563790135e-06, 'epoch': 5.645645645645645}

Step 9500: {'loss': 0.10828980445861816, 'grad_norm': 13.148701667785645, 'learning_rate': 9.28465961006646e-06, 'epoch': 5.7057057057057055}

Step 9600: {'loss': 0.11340706825256347, 'grad_norm': 10.825422286987305, 'learning_rate': 9.07572005674346e-06, 'epoch': 5.7657657657657655}

Step 9700: {'loss': 0.11299592018127441, 'grad_norm': 9.55984115600586, 'learning_rate': 8.867186735178911e-06, 'epoch': 5.8258258258258255}

Step 9800: {'loss': 0.10352359771728516, 'grad_norm': 7.634352207183838, 'learning_rate': 8.659151298187018e-06, 'epoch': 5.885885885885886}

Step 9900: {'loss': 0.11289718627929687, 'grad_norm': 3.7177884578704834, 'learning_rate': 8.451705179755947e-06, 'epoch': 5.945945945945946}

Epoch 6 completed!

Step 9990: {'eval_loss': 0.12928639352321625, 'eval_accuracy': 0.925168918918919, 'eval_f1': 0.9249534135185499, 'eval_precision': 0.9276248725790011, 'eval_recall': 0.9222972972972973, 'eval_runtime': 74.2724, 'eval_samples_per_second': 79.707, 'eval_steps_per_second': 2.491, 'epoch': 6.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 7/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 10000: {'loss': 0.11246064186096191, 'grad_norm': 13.565714836120605, 'learning_rate': 8.244939554861512e-06, 'epoch': 6.006006006006006}

Step 10100: {'loss': 0.09990007400512696, 'grad_norm': 7.279462814331055, 'learning_rate': 8.038945299394722e-06, 'epoch': 6.066066066066066}

Step 10200: {'loss': 0.09874706268310547, 'grad_norm': 14.974538803100586, 'learning_rate': 7.833812950220783e-06, 'epoch': 6.126126126126126}

Step 10300: {'loss': 0.10326835632324219, 'grad_norm': 4.528919696807861, 'learning_rate': 7.62963266538707e-06, 'epoch': 6.186186186186186}

Step 10400: {'loss': 0.1024312686920166, 'grad_norm': 8.73178768157959, 'learning_rate': 7.426494184497655e-06, 'epoch': 6.246246246246246}

Step 10500: {'loss': 0.10609149932861328, 'grad_norm': 5.799397945404053, 'learning_rate': 7.224486789271671e-06, 'epoch': 6.306306306306306}

Step 10600: {'loss': 0.10322891235351563, 'grad_norm': 8.523012161254883, 'learning_rate': 7.0236992643029854e-06, 'epoch': 6.366366366366367}

Step 10700: {'loss': 0.09850916862487794, 'grad_norm': 9.084306716918945, 'learning_rate': 6.824219858038339e-06, 'epoch': 6.426426426426427}

Step 10800: {'loss': 0.09843211174011231, 'grad_norm': 9.037211418151855, 'learning_rate': 6.626136243991124e-06, 'epoch': 6.486486486486487}

Step 10900: {'loss': 0.09978431701660156, 'grad_norm': 4.140011310577393, 'learning_rate': 6.429535482207847e-06, 'epoch': 6.546546546546547}

Step 11000: {'loss': 0.09797523498535156, 'grad_norm': 10.812464714050293, 'learning_rate': 6.234503981004265e-06, 'epoch': 6.606606606606607}

Step 11100: {'loss': 0.10673851013183594, 'grad_norm': 4.26879358291626, 'learning_rate': 6.0411274589878834e-06, 'epoch': 6.666666666666667}

Step 11200: {'loss': 0.10286201477050781, 'grad_norm': 6.903580665588379, 'learning_rate': 5.849490907383659e-06, 'epoch': 6.726726726726727}

Step 11300: {'loss': 0.10144908905029297, 'grad_norm': 11.479022026062012, 'learning_rate': 5.659678552679371e-06, 'epoch': 6.786786786786787}

Step 11400: {'loss': 0.1001594352722168, 'grad_norm': 4.351805210113525, 'learning_rate': 5.471773819607095e-06, 'epoch': 6.846846846846847}

Step 11500: {'loss': 0.09492083549499512, 'grad_norm': 6.101603031158447, 'learning_rate': 5.285859294477054e-06, 'epoch': 6.906906906906907}

Step 11600: {'loss': 0.10236865997314454, 'grad_norm': 2.085240125656128, 'learning_rate': 5.102016688880014e-06, 'epoch': 6.966966966966967}

Epoch 7 completed!

Step 11655: {'eval_loss': 0.14158236980438232, 'eval_accuracy': 0.9236486486486486, 'eval_f1': 0.9201413427561838, 'eval_precision': 0.9644444444444444, 'eval_recall': 0.8797297297297297, 'eval_runtime': 74.5054, 'eval_samples_per_second': 79.457, 'eval_steps_per_second': 2.483, 'epoch': 7.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 8/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 11700: {'loss': 0.09496231079101562, 'grad_norm': 17.155927658081055, 'learning_rate': 4.920326803774047e-06, 'epoch': 7.027027027027027}

Step 11800: {'loss': 0.09090558052062989, 'grad_norm': 6.906479358673096, 'learning_rate': 4.7408694939716095e-06, 'epoch': 7.087087087087087}

Step 11900: {'loss': 0.09163516044616699, 'grad_norm': 7.762651443481445, 'learning_rate': 4.5637236330424005e-06, 'epoch': 7.147147147147147}

Step 12000: {'loss': 0.09905060768127441, 'grad_norm': 6.030119895935059, 'learning_rate': 4.3889670786475195e-06, 'epoch': 7.207207207207207}

Step 12100: {'loss': 0.09145694732666015, 'grad_norm': 12.780887603759766, 'learning_rate': 4.216676638320135e-06, 'epoch': 7.267267267267267}

Step 12200: {'loss': 0.09688514709472656, 'grad_norm': 2.6940903663635254, 'learning_rate': 4.0469280357076625e-06, 'epoch': 7.327327327327327}

Step 12300: {'loss': 0.09481822967529296, 'grad_norm': 9.071124076843262, 'learning_rate': 3.879795877290354e-06, 'epoch': 7.387387387387387}

Step 12400: {'loss': 0.09754085540771484, 'grad_norm': 7.386863708496094, 'learning_rate': 3.7153536195908813e-06, 'epoch': 7.4474474474474475}

Step 12500: {'loss': 0.0900242805480957, 'grad_norm': 5.737845420837402, 'learning_rate': 3.5536735368893436e-06, 'epoch': 7.5075075075075075}

Step 12600: {'loss': 0.09481653213500976, 'grad_norm': 12.253084182739258, 'learning_rate': 3.3948266894578796e-06, 'epoch': 7.5675675675675675}

Step 12700: {'loss': 0.08786120414733886, 'grad_norm': 11.667409896850586, 'learning_rate': 3.238882892328864e-06, 'epoch': 7.627627627627628}

Step 12800: {'loss': 0.09223568916320801, 'grad_norm': 10.79893684387207, 'learning_rate': 3.085910684610374e-06, 'epoch': 7.687687687687688}

Step 12900: {'loss': 0.09035287857055664, 'grad_norm': 3.5115721225738525, 'learning_rate': 2.9359772993624635e-06, 'epoch': 7.747747747747748}

Step 13000: {'loss': 0.08677361488342285, 'grad_norm': 1.761216640472412, 'learning_rate': 2.7891486340474683e-06, 'epoch': 7.807807807807808}

Step 13100: {'loss': 0.09181534767150878, 'grad_norm': 4.090023517608643, 'learning_rate': 2.6454892215672767e-06, 'epoch': 7.867867867867868}

Step 13200: {'loss': 0.09574602127075195, 'grad_norm': 11.904359817504883, 'learning_rate': 2.5050622019003934e-06, 'epoch': 7.927927927927928}

Step 13300: {'loss': 0.09141785621643067, 'grad_norm': 2.724421262741089, 'learning_rate': 2.3679292943511858e-06, 'epoch': 7.987987987987988}

Epoch 8 completed!

Step 13320: {'eval_loss': 0.13187198340892792, 'eval_accuracy': 0.9246621621621621, 'eval_f1': 0.9220824598183088, 'eval_precision': 0.9547756874095513, 'eval_recall': 0.8915540540540541, 'eval_runtime': 74.3484, 'eval_samples_per_second': 79.625, 'eval_steps_per_second': 2.488, 'epoch': 8.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 9/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 13400: {'loss': 0.08943692207336426, 'grad_norm': 12.377921104431152, 'learning_rate': 2.234150770423518e-06, 'epoch': 8.048048048048049}

Step 13500: {'loss': 0.08545519828796387, 'grad_norm': 4.85400915145874, 'learning_rate': 2.103785427330739e-06, 'epoch': 8.108108108108109}

Step 13600: {'loss': 0.08298626899719239, 'grad_norm': 6.124695301055908, 'learning_rate': 1.976890562153623e-06, 'epoch': 8.168168168168169}

Step 13700: {'loss': 0.09379979133605958, 'grad_norm': 2.990441083908081, 'learning_rate': 1.8535219466576327e-06, 'epoch': 8.228228228228229}

Step 13800: {'loss': 0.0880870532989502, 'grad_norm': 8.557387351989746, 'learning_rate': 1.7337338027805907e-06, 'epoch': 8.288288288288289}

Step 13900: {'loss': 0.09275846481323242, 'grad_norm': 13.55320930480957, 'learning_rate': 1.6175787788014974e-06, 'epoch': 8.348348348348349}

Step 14000: {'loss': 0.08900413513183594, 'grad_norm': 1.0611329078674316, 'learning_rate': 1.505107926201007e-06, 'epoch': 8.408408408408409}

Step 14100: {'loss': 0.09072737693786621, 'grad_norm': 5.5834455490112305, 'learning_rate': 1.3963706772237161e-06, 'epoch': 8.468468468468469}

Step 14200: {'loss': 0.0843115234375, 'grad_norm': 4.297295093536377, 'learning_rate': 1.291414823152104e-06, 'epoch': 8.528528528528529}

Step 14300: {'loss': 0.08438068389892578, 'grad_norm': 2.257211685180664, 'learning_rate': 1.19028649330172e-06, 'epoch': 8.588588588588589}

Step 14400: {'loss': 0.08676578521728516, 'grad_norm': 11.108504295349121, 'learning_rate': 1.0930301347468154e-06, 'epoch': 8.64864864864865}

Step 14500: {'loss': 0.08998684883117676, 'grad_norm': 13.433758735656738, 'learning_rate': 9.996884927853312e-07, 'epoch': 8.70870870870871}

Step 14600: {'loss': 0.08900635719299316, 'grad_norm': 6.341543197631836, 'learning_rate': 9.103025921518482e-07, 'epoch': 8.76876876876877}

Step 14700: {'loss': 0.08391419410705567, 'grad_norm': 10.024595260620117, 'learning_rate': 8.249117189867395e-07, 'epoch': 8.82882882882883}

Step 14800: {'loss': 0.08903851509094238, 'grad_norm': 1.334892749786377, 'learning_rate': 7.435534035694548e-07, 'epoch': 8.88888888888889}

Step 14900: {'loss': 0.08668091773986816, 'grad_norm': 0.9051327705383301, 'learning_rate': 6.662634038235328e-07, 'epoch': 8.94894894894895}

Epoch 9 completed!

Step 14985: {'eval_loss': 0.12783268094062805, 'eval_accuracy': 0.9283783783783783, 'eval_f1': 0.9262865090403338, 'eval_precision': 0.9541547277936963, 'eval_recall': 0.9, 'eval_runtime': 74.2641, 'eval_samples_per_second': 79.716, 'eval_steps_per_second': 2.491, 'epoch': 9.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 10/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 15000: {'loss': 0.0885927677154541, 'grad_norm': 2.325742483139038, 'learning_rate': 5.930756896005707e-07, 'epoch': 9.00900900900901}

Step 15100: {'loss': 0.08472514152526855, 'grad_norm': 1.7846401929855347, 'learning_rate': 5.240224277500827e-07, 'epoch': 9.06906906906907}

Step 15200: {'loss': 0.08511595726013184, 'grad_norm': 5.536650657653809, 'learning_rate': 4.591339679818041e-07, 'epoch': 9.12912912912913}

Step 15300: {'loss': 0.08316420555114747, 'grad_norm': 4.952333450317383, 'learning_rate': 3.984388295266284e-07, 'epoch': 9.18918918918919}

Step 15400: {'loss': 0.09250394821166992, 'grad_norm': 9.932172775268555, 'learning_rate': 3.4196368860208495e-07, 'epoch': 9.24924924924925}

Step 15500: {'loss': 0.08407977104187012, 'grad_norm': 2.937612295150757, 'learning_rate': 2.897333666878299e-07, 'epoch': 9.30930930930931}

Step 15600: {'loss': 0.0890665340423584, 'grad_norm': 2.4790310859680176, 'learning_rate': 2.4177081961631264e-07, 'epoch': 9.36936936936937}

Step 15700: {'loss': 0.08846085548400878, 'grad_norm': 5.107147216796875, 'learning_rate': 1.980971274834287e-07, 'epoch': 9.42942942942943}

Step 15800: {'loss': 0.08584747314453126, 'grad_norm': 4.222995281219482, 'learning_rate': 1.5873148538356752e-07, 'epoch': 9.48948948948949}

Step 15900: {'loss': 0.08775784492492676, 'grad_norm': 2.190493106842041, 'learning_rate': 1.2369119497314674e-07, 'epoch': 9.54954954954955}

Step 16000: {'loss': 0.08486682891845704, 'grad_norm': 12.250544548034668, 'learning_rate': 9.299165686633471e-08, 'epoch': 9.60960960960961}

Step 16100: {'loss': 0.08523576736450195, 'grad_norm': 4.236150741577148, 'learning_rate': 6.664636386630286e-08, 'epoch': 9.66966966966967}

Step 16200: {'loss': 0.08658184051513672, 'grad_norm': 6.419607162475586, 'learning_rate': 4.466689503498045e-08, 'epoch': 9.72972972972973}

Step 16300: {'loss': 0.0770138931274414, 'grad_norm': 5.289453029632568, 'learning_rate': 2.7062910603921078e-08, 'epoch': 9.78978978978979}

Step 16400: {'loss': 0.08510739326477051, 'grad_norm': 8.8341064453125, 'learning_rate': 1.3842147728522215e-08, 'epoch': 9.84984984984985}

Step 16500: {'loss': 0.08290941238403321, 'grad_norm': 3.004469871520996, 'learning_rate': 5.010417087452091e-09, 'epoch': 9.90990990990991}

Step 16600: {'loss': 0.08513028144836426, 'grad_norm': 1.6270259618759155, 'learning_rate': 5.716003287936645e-10, 'epoch': 9.96996996996997}

Epoch 10 completed!

Step 16650: {'eval_loss': 0.12540394067764282, 'eval_accuracy': 0.9287162162162163, 'eval_f1': 0.9270401106500692, 'eval_precision': 0.9493626062322946, 'eval_recall': 0.9057432432432433, 'eval_runtime': 74.3929, 'eval_samples_per_second': 79.577, 'eval_steps_per_second': 2.487, 'epoch': 10.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 16650: {'train_runtime': 10776.199, 'train_samples_per_second': 49.439, 'train_steps_per_second': 1.545, 'total_flos': 2.7757476441072e+16, 'train_loss': 0.17304087057485953, 'epoch': 10.0}

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 16650: {'eval_loss': 0.12540394067764282, 'eval_accuracy': 0.9287162162162163, 'eval_f1': 0.9270401106500692, 'eval_precision': 0.9493626062322946, 'eval_recall': 0.9057432432432433, 'eval_runtime': 74.3463, 'eval_samples_per_second': 79.627, 'eval_steps_per_second': 2.488, 'epoch': 10.0}

--- 4-Layer-Standard_a0.3_t3.0 Results ---
  Accuracy:  92.87%
  F1 Score:  0.9270
  Precision: 0.9494
  Recall:    0.9057
  Loss:      0.1254
  Time:      179.6 min

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Results saved (6 total)

######################################################################
# Run 3/4: 4-Layer-Standard | alpha=0.3 | temp=5.0
######################################################################

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Student parameters: 32,485,634 (32.5M)

Starting training...

============================================================

Starting Epoch 1/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 100: {'loss': 0.8666838836669922, 'grad_norm': 3.8106772899627686, 'learning_rate': 1.1891891891891893e-06, 'epoch': 0.06006006006006006}

Step 200: {'loss': 0.832338638305664, 'grad_norm': 5.252133369445801, 'learning_rate': 2.3903903903903904e-06, 'epoch': 0.12012012012012012}

Step 300: {'loss': 0.8220606231689453, 'grad_norm': 2.2914159297943115, 'learning_rate': 3.5915915915915917e-06, 'epoch': 0.18018018018018017}

Step 400: {'loss': 0.8147738647460937, 'grad_norm': 4.700761795043945, 'learning_rate': 4.792792792792793e-06, 'epoch': 0.24024024024024024}

Step 500: {'loss': 0.7977042388916016, 'grad_norm': 9.367033004760742, 'learning_rate': 5.993993993993994e-06, 'epoch': 0.3003003003003003}

Step 600: {'loss': 0.6878897094726563, 'grad_norm': 33.28657531738281, 'learning_rate': 7.195195195195196e-06, 'epoch': 0.36036036036036034}

Step 700: {'loss': 0.47601348876953126, 'grad_norm': 5.853061676025391, 'learning_rate': 8.396396396396397e-06, 'epoch': 0.42042042042042044}

Step 800: {'loss': 0.4135348510742187, 'grad_norm': 3.5557398796081543, 'learning_rate': 9.597597597597599e-06, 'epoch': 0.4804804804804805}

Step 900: {'loss': 0.3814912033081055, 'grad_norm': 18.413158416748047, 'learning_rate': 1.07987987987988e-05, 'epoch': 0.5405405405405406}

Step 1000: {'loss': 0.382620735168457, 'grad_norm': 3.249441146850586, 'learning_rate': 1.2e-05, 'epoch': 0.6006006006006006}

Step 1100: {'loss': 0.3510640716552734, 'grad_norm': 46.59770202636719, 'learning_rate': 1.3201201201201202e-05, 'epoch': 0.6606606606606606}

Step 1200: {'loss': 0.4051141357421875, 'grad_norm': 4.035879611968994, 'learning_rate': 1.4402402402402404e-05, 'epoch': 0.7207207207207207}

Step 1300: {'loss': 0.33113147735595705, 'grad_norm': 39.61067581176758, 'learning_rate': 1.5603603603603605e-05, 'epoch': 0.7807807807807807}

Step 1400: {'loss': 0.33059982299804686, 'grad_norm': 45.645591735839844, 'learning_rate': 1.6804804804804807e-05, 'epoch': 0.8408408408408409}

Step 1500: {'loss': 0.34098091125488283, 'grad_norm': 6.518669128417969, 'learning_rate': 1.8006006006006005e-05, 'epoch': 0.9009009009009009}

Step 1600: {'loss': 0.30062261581420896, 'grad_norm': 19.147846221923828, 'learning_rate': 1.9207207207207207e-05, 'epoch': 0.960960960960961}

Epoch 1 completed!

Step 1665: {'eval_loss': 0.242932990193367, 'eval_accuracy': 0.8721283783783784, 'eval_f1': 0.8685992015275126, 'eval_precision': 0.8932524098536238, 'eval_recall': 0.8452702702702702, 'eval_runtime': 74.2406, 'eval_samples_per_second': 79.741, 'eval_steps_per_second': 2.492, 'epoch': 1.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 2/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 1700: {'loss': 0.2840491485595703, 'grad_norm': 22.287078857421875, 'learning_rate': 1.9999745954064855e-05, 'epoch': 1.021021021021021}

Step 1800: {'loss': 0.26453704833984376, 'grad_norm': 12.361300468444824, 'learning_rate': 1.9996054179825038e-05, 'epoch': 1.0810810810810811}

Step 1900: {'loss': 0.26866510391235354, 'grad_norm': 3.5149168968200684, 'learning_rate': 1.998796902380012e-05, 'epoch': 1.1411411411411412}

Step 2000: {'loss': 0.27566232681274416, 'grad_norm': 27.276302337646484, 'learning_rate': 1.997549403950997e-05, 'epoch': 1.2012012012012012}

Step 2100: {'loss': 0.2561023712158203, 'grad_norm': 41.69358825683594, 'learning_rate': 1.995863470985492e-05, 'epoch': 1.2612612612612613}

Step 2200: {'loss': 0.2928031921386719, 'grad_norm': 16.151586532592773, 'learning_rate': 1.9937398444705953e-05, 'epoch': 1.3213213213213213}

Step 2300: {'loss': 0.271018009185791, 'grad_norm': 2.971072196960449, 'learning_rate': 1.991179457764798e-05, 'epoch': 1.3813813813813813}

Step 2400: {'loss': 0.27055116653442385, 'grad_norm': 26.718252182006836, 'learning_rate': 1.988183436187763e-05, 'epoch': 1.4414414414414414}

Step 2500: {'loss': 0.2560508537292481, 'grad_norm': 5.155185699462891, 'learning_rate': 1.9847530965257328e-05, 'epoch': 1.5015015015015014}

Step 2600: {'loss': 0.28193742752075196, 'grad_norm': 11.728209495544434, 'learning_rate': 1.9808899464527874e-05, 'epoch': 1.5615615615615615}

Step 2700: {'loss': 0.24516637802124022, 'grad_norm': 8.867935180664062, 'learning_rate': 1.9765956838682032e-05, 'epoch': 1.6216216216216215}

Step 2800: {'loss': 0.23502157211303712, 'grad_norm': 16.537443161010742, 'learning_rate': 1.971872196150208e-05, 'epoch': 1.6816816816816815}

Step 2900: {'loss': 0.24723615646362304, 'grad_norm': 44.462684631347656, 'learning_rate': 1.9667215593264558e-05, 'epoch': 1.7417417417417418}

Step 3000: {'loss': 0.2733496856689453, 'grad_norm': 32.36073303222656, 'learning_rate': 1.9611460371615865e-05, 'epoch': 1.8018018018018018}

Step 3100: {'loss': 0.24919889450073243, 'grad_norm': 12.492915153503418, 'learning_rate': 1.955148080162279e-05, 'epoch': 1.8618618618618619}

Step 3200: {'loss': 0.24193666458129884, 'grad_norm': 33.66829299926758, 'learning_rate': 1.9487303245002217e-05, 'epoch': 1.921921921921922}

Step 3300: {'loss': 0.24578910827636719, 'grad_norm': 5.591871738433838, 'learning_rate': 1.9418955908534863e-05, 'epoch': 1.981981981981982}

Epoch 2 completed!

Step 3330: {'eval_loss': 0.22611463069915771, 'eval_accuracy': 0.8898648648648648, 'eval_f1': 0.8834465498748659, 'eval_precision': 0.9381169324221716, 'eval_recall': 0.8347972972972973, 'eval_runtime': 74.2796, 'eval_samples_per_second': 79.699, 'eval_steps_per_second': 2.491, 'epoch': 2.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 3/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 3400: {'loss': 0.24633501052856446, 'grad_norm': 53.69546890258789, 'learning_rate': 1.9346468831668065e-05, 'epoch': 2.042042042042042}

Step 3500: {'loss': 0.21317193984985353, 'grad_norm': 42.169578552246094, 'learning_rate': 1.926987387331309e-05, 'epoch': 2.1021021021021022}

Step 3600: {'loss': 0.20545307159423828, 'grad_norm': 37.98046112060547, 'learning_rate': 1.918920469784278e-05, 'epoch': 2.1621621621621623}

Step 3700: {'loss': 0.2067780876159668, 'grad_norm': 10.583910942077637, 'learning_rate': 1.9104496760295675e-05, 'epoch': 2.2222222222222223}

Step 3800: {'loss': 0.21077800750732423, 'grad_norm': 22.096023559570312, 'learning_rate': 1.9015787290793092e-05, 'epoch': 2.2822822822822824}

Step 3900: {'loss': 0.2014438056945801, 'grad_norm': 12.348724365234375, 'learning_rate': 1.892311527817608e-05, 'epoch': 2.3423423423423424}

Step 4000: {'loss': 0.2304578971862793, 'grad_norm': 28.31673240661621, 'learning_rate': 1.8826521452869348e-05, 'epoch': 2.4024024024024024}

Step 4100: {'loss': 0.23557144165039062, 'grad_norm': 26.75278091430664, 'learning_rate': 1.872604826897979e-05, 'epoch': 2.4624624624624625}

Step 4200: {'loss': 0.21506593704223634, 'grad_norm': 3.1063928604125977, 'learning_rate': 1.8621739885637407e-05, 'epoch': 2.5225225225225225}

Step 4300: {'loss': 0.21092971801757812, 'grad_norm': 48.27152633666992, 'learning_rate': 1.8513642147586855e-05, 'epoch': 2.5825825825825826}

Step 4400: {'loss': 0.21748327255249023, 'grad_norm': 13.238458633422852, 'learning_rate': 1.8401802565038135e-05, 'epoch': 2.6426426426426426}

Step 4500: {'loss': 0.20889036178588868, 'grad_norm': 2.616213321685791, 'learning_rate': 1.8286270292785337e-05, 'epoch': 2.7027027027027026}

Step 4600: {'loss': 0.2083060073852539, 'grad_norm': 34.7511100769043, 'learning_rate': 1.81670961086025e-05, 'epoch': 2.7627627627627627}

Step 4700: {'loss': 0.21121105194091797, 'grad_norm': 35.603057861328125, 'learning_rate': 1.8044332390926224e-05, 'epoch': 2.8228228228228227}

Step 4800: {'loss': 0.21505506515502928, 'grad_norm': 18.03526496887207, 'learning_rate': 1.7918033095834714e-05, 'epoch': 2.8828828828828827}

Step 4900: {'loss': 0.21613855361938478, 'grad_norm': 4.1265130043029785, 'learning_rate': 1.778825373333347e-05, 'epoch': 2.942942942942943}

Epoch 3 completed!

Step 4995: {'eval_loss': 0.18659760057926178, 'eval_accuracy': 0.895777027027027, 'eval_f1': 0.898569784645734, 'eval_precision': 0.8751200768491835, 'eval_recall': 0.9233108108108108, 'eval_runtime': 74.1951, 'eval_samples_per_second': 79.79, 'eval_steps_per_second': 2.493, 'epoch': 3.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 4/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 5000: {'loss': 0.18909881591796876, 'grad_norm': 10.5579252243042, 'learning_rate': 1.7655051342958005e-05, 'epoch': 3.003003003003003}

Step 5100: {'loss': 0.18949296951293945, 'grad_norm': 16.809410095214844, 'learning_rate': 1.7518484468704283e-05, 'epoch': 3.063063063063063}

Step 5200: {'loss': 0.18928190231323241, 'grad_norm': 5.801678657531738, 'learning_rate': 1.7378613133297974e-05, 'epoch': 3.123123123123123}

Step 5300: {'loss': 0.1780076026916504, 'grad_norm': 4.703674793243408, 'learning_rate': 1.7235498811813757e-05, 'epoch': 3.1831831831831834}

Step 5400: {'loss': 0.18407684326171875, 'grad_norm': 6.929392337799072, 'learning_rate': 1.708920440465632e-05, 'epoch': 3.2432432432432434}

Step 5500: {'loss': 0.18430477142333984, 'grad_norm': 15.07105541229248, 'learning_rate': 1.6939794209914907e-05, 'epoch': 3.3033033033033035}

Step 5600: {'loss': 0.18166847229003907, 'grad_norm': 6.303361892700195, 'learning_rate': 1.6787333895103535e-05, 'epoch': 3.3633633633633635}

Step 5700: {'loss': 0.1762300491333008, 'grad_norm': 10.743158340454102, 'learning_rate': 1.6631890468299402e-05, 'epoch': 3.4234234234234235}

Step 5800: {'loss': 0.1642911148071289, 'grad_norm': 23.84403419494629, 'learning_rate': 1.6473532248692016e-05, 'epoch': 3.4834834834834836}

Step 5900: {'loss': 0.17150468826293946, 'grad_norm': 31.291913986206055, 'learning_rate': 1.6312328836556152e-05, 'epoch': 3.5435435435435436}

Step 6000: {'loss': 0.15590657234191896, 'grad_norm': 4.015378475189209, 'learning_rate': 1.6148351082661707e-05, 'epoch': 3.6036036036036037}

Step 6100: {'loss': 0.1654886245727539, 'grad_norm': 10.991424560546875, 'learning_rate': 1.5981671057133975e-05, 'epoch': 3.6636636636636637}

Step 6200: {'loss': 0.1525913143157959, 'grad_norm': 9.802515029907227, 'learning_rate': 1.5812362017777965e-05, 'epoch': 3.7237237237237237}

Step 6300: {'loss': 0.15838540077209473, 'grad_norm': 15.355088233947754, 'learning_rate': 1.564049837788079e-05, 'epoch': 3.7837837837837838}

Step 6400: {'loss': 0.14495542526245117, 'grad_norm': 11.015748977661133, 'learning_rate': 1.546615567350612e-05, 'epoch': 3.843843843843844}

Step 6500: {'loss': 0.14321446418762207, 'grad_norm': 18.28251075744629, 'learning_rate': 1.5289410530295233e-05, 'epoch': 3.903903903903904}

Step 6600: {'loss': 0.1396548080444336, 'grad_norm': 16.150283813476562, 'learning_rate': 1.5110340629789148e-05, 'epoch': 3.963963963963964}

Epoch 4 completed!

Step 6660: {'eval_loss': 0.1698869913816452, 'eval_accuracy': 0.910472972972973, 'eval_f1': 0.9064595834804094, 'eval_precision': 0.9490022172949002, 'eval_recall': 0.8675675675675676, 'eval_runtime': 74.2776, 'eval_samples_per_second': 79.701, 'eval_steps_per_second': 2.491, 'epoch': 4.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 5/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 6700: {'loss': 0.1445590591430664, 'grad_norm': 4.456158638000488, 'learning_rate': 1.4929024675286688e-05, 'epoch': 4.024024024024024}

Step 6800: {'loss': 0.1333825969696045, 'grad_norm': 8.199067115783691, 'learning_rate': 1.4745542357253462e-05, 'epoch': 4.084084084084084}

Step 6900: {'loss': 0.13304723739624025, 'grad_norm': 12.301314353942871, 'learning_rate': 1.4559974318296984e-05, 'epoch': 4.1441441441441444}

Step 7000: {'loss': 0.14360554695129393, 'grad_norm': 11.891368865966797, 'learning_rate': 1.4372402117723314e-05, 'epoch': 4.2042042042042045}

Step 7100: {'loss': 0.13406484603881835, 'grad_norm': 7.244290828704834, 'learning_rate': 1.4182908195690799e-05, 'epoch': 4.2642642642642645}

Step 7200: {'loss': 0.12616236686706542, 'grad_norm': 24.330677032470703, 'learning_rate': 1.399157583697666e-05, 'epoch': 4.324324324324325}

Step 7300: {'loss': 0.13420272827148438, 'grad_norm': 13.784927368164062, 'learning_rate': 1.3798489134372361e-05, 'epoch': 4.384384384384385}

Step 7400: {'loss': 0.13872023582458495, 'grad_norm': 3.665956974029541, 'learning_rate': 1.3603732951723874e-05, 'epoch': 4.444444444444445}

Step 7500: {'loss': 0.1198786449432373, 'grad_norm': 4.657100677490234, 'learning_rate': 1.3407392886633008e-05, 'epoch': 4.504504504504505}

Step 7600: {'loss': 0.13134459495544434, 'grad_norm': 1.9271068572998047, 'learning_rate': 1.3209555232836284e-05, 'epoch': 4.564564564564565}

Step 7700: {'loss': 0.12617985725402833, 'grad_norm': 17.18149185180664, 'learning_rate': 1.301030694227784e-05, 'epoch': 4.624624624624625}

Step 7800: {'loss': 0.12710414886474608, 'grad_norm': 22.23927116394043, 'learning_rate': 1.2809735586893028e-05, 'epoch': 4.684684684684685}

Step 7900: {'loss': 0.12878236770629883, 'grad_norm': 3.247939348220825, 'learning_rate': 1.2607929320119547e-05, 'epoch': 4.744744744744745}

Step 8000: {'loss': 0.13340176582336427, 'grad_norm': 16.693506240844727, 'learning_rate': 1.2404976838152977e-05, 'epoch': 4.804804804804805}

Step 8100: {'loss': 0.13116948127746583, 'grad_norm': 5.441532611846924, 'learning_rate': 1.2200967340963774e-05, 'epoch': 4.864864864864865}

Step 8200: {'loss': 0.11962742805480957, 'grad_norm': 9.006258964538574, 'learning_rate': 1.1995990493092849e-05, 'epoch': 4.924924924924925}

Step 8300: {'loss': 0.1370570468902588, 'grad_norm': 7.063545227050781, 'learning_rate': 1.1790136384242957e-05, 'epoch': 4.984984984984985}

Epoch 5 completed!

Step 8325: {'eval_loss': 0.13362789154052734, 'eval_accuracy': 0.9241554054054054, 'eval_f1': 0.9219266214571379, 'eval_precision': 0.9498387674668578, 'eval_recall': 0.8956081081081081, 'eval_runtime': 74.1925, 'eval_samples_per_second': 79.792, 'eval_steps_per_second': 2.494, 'epoch': 5.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 6/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 8400: {'loss': 0.11747761726379395, 'grad_norm': 23.26479721069336, 'learning_rate': 1.158349548968323e-05, 'epoch': 5.045045045045045}

Step 8500: {'loss': 0.10986943244934082, 'grad_norm': 20.511478424072266, 'learning_rate': 1.1376158630484258e-05, 'epoch': 5.105105105105105}

Step 8600: {'loss': 0.11459230422973633, 'grad_norm': 16.461963653564453, 'learning_rate': 1.116821693360115e-05, 'epoch': 5.165165165165165}

Step 8700: {'loss': 0.12563308715820312, 'grad_norm': 0.8993654251098633, 'learning_rate': 1.0959761791822208e-05, 'epoch': 5.225225225225225}

Step 8800: {'loss': 0.10998669624328614, 'grad_norm': 3.731107473373413, 'learning_rate': 1.0750884823600713e-05, 'epoch': 5.285285285285285}

Step 8900: {'loss': 0.11690789222717285, 'grad_norm': 4.247503280639648, 'learning_rate': 1.0541677832787569e-05, 'epoch': 5.345345345345345}

Step 9000: {'loss': 0.12106363296508789, 'grad_norm': 9.38058853149414, 'learning_rate': 1.0332232768282429e-05, 'epoch': 5.405405405405405}

Step 9100: {'loss': 0.11317317962646484, 'grad_norm': 3.1303839683532715, 'learning_rate': 1.0122641683621102e-05, 'epoch': 5.465465465465465}

Step 9200: {'loss': 0.11651348114013672, 'grad_norm': 1.097461462020874, 'learning_rate': 9.912996696516946e-06, 'epoch': 5.525525525525525}

Step 9300: {'loss': 0.11728322982788086, 'grad_norm': 6.520213603973389, 'learning_rate': 9.703389948374077e-06, 'epoch': 5.585585585585585}

Step 9400: {'loss': 0.11790247917175294, 'grad_norm': 5.595644474029541, 'learning_rate': 9.493913563790135e-06, 'epoch': 5.645645645645645}

Step 9500: {'loss': 0.11252140045166016, 'grad_norm': 20.813251495361328, 'learning_rate': 9.28465961006646e-06, 'epoch': 5.7057057057057055}

Step 9600: {'loss': 0.11737711906433106, 'grad_norm': 10.91583251953125, 'learning_rate': 9.07572005674346e-06, 'epoch': 5.7657657657657655}

Step 9700: {'loss': 0.11902504920959472, 'grad_norm': 5.948130130767822, 'learning_rate': 8.867186735178911e-06, 'epoch': 5.8258258258258255}

Step 9800: {'loss': 0.11023812294006348, 'grad_norm': 4.08749532699585, 'learning_rate': 8.659151298187018e-06, 'epoch': 5.885885885885886}

Step 9900: {'loss': 0.1189330291748047, 'grad_norm': 3.6620779037475586, 'learning_rate': 8.451705179755947e-06, 'epoch': 5.945945945945946}

Epoch 6 completed!

Step 9990: {'eval_loss': 0.1464603990316391, 'eval_accuracy': 0.9168918918918919, 'eval_f1': 0.9189456342668864, 'eval_precision': 0.8967845659163988, 'eval_recall': 0.9422297297297297, 'eval_runtime': 74.3257, 'eval_samples_per_second': 79.649, 'eval_steps_per_second': 2.489, 'epoch': 6.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 7/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 10000: {'loss': 0.11735665321350097, 'grad_norm': 15.025830268859863, 'learning_rate': 8.244939554861512e-06, 'epoch': 6.006006006006006}

Step 10100: {'loss': 0.10212605476379394, 'grad_norm': 10.404693603515625, 'learning_rate': 8.038945299394722e-06, 'epoch': 6.066066066066066}

Step 10200: {'loss': 0.10375327110290528, 'grad_norm': 10.753870964050293, 'learning_rate': 7.833812950220783e-06, 'epoch': 6.126126126126126}

Step 10300: {'loss': 0.10652069091796874, 'grad_norm': 8.811513900756836, 'learning_rate': 7.62963266538707e-06, 'epoch': 6.186186186186186}

Step 10400: {'loss': 0.10895855903625488, 'grad_norm': 2.684464693069458, 'learning_rate': 7.426494184497655e-06, 'epoch': 6.246246246246246}

Step 10500: {'loss': 0.10836736679077148, 'grad_norm': 8.708229064941406, 'learning_rate': 7.224486789271671e-06, 'epoch': 6.306306306306306}

Step 10600: {'loss': 0.10341370582580567, 'grad_norm': 10.461246490478516, 'learning_rate': 7.0236992643029854e-06, 'epoch': 6.366366366366367}

Step 10700: {'loss': 0.10085442543029785, 'grad_norm': 9.427582740783691, 'learning_rate': 6.824219858038339e-06, 'epoch': 6.426426426426427}

Step 10800: {'loss': 0.09941165924072265, 'grad_norm': 10.0701322555542, 'learning_rate': 6.626136243991124e-06, 'epoch': 6.486486486486487}

Step 10900: {'loss': 0.10442910194396973, 'grad_norm': 3.9925992488861084, 'learning_rate': 6.429535482207847e-06, 'epoch': 6.546546546546547}

Step 11000: {'loss': 0.10240419387817383, 'grad_norm': 12.09370231628418, 'learning_rate': 6.234503981004265e-06, 'epoch': 6.606606606606607}

Step 11100: {'loss': 0.10728601455688476, 'grad_norm': 2.2177011966705322, 'learning_rate': 6.0411274589878834e-06, 'epoch': 6.666666666666667}

Step 11200: {'loss': 0.10782301902770997, 'grad_norm': 6.093837738037109, 'learning_rate': 5.849490907383659e-06, 'epoch': 6.726726726726727}

Step 11300: {'loss': 0.10595291137695312, 'grad_norm': 8.775591850280762, 'learning_rate': 5.659678552679371e-06, 'epoch': 6.786786786786787}

Step 11400: {'loss': 0.10081993103027344, 'grad_norm': 5.091248989105225, 'learning_rate': 5.471773819607095e-06, 'epoch': 6.846846846846847}

Step 11500: {'loss': 0.09812739372253418, 'grad_norm': 7.760505199432373, 'learning_rate': 5.285859294477054e-06, 'epoch': 6.906906906906907}

Step 11600: {'loss': 0.10281373977661133, 'grad_norm': 13.423057556152344, 'learning_rate': 5.102016688880014e-06, 'epoch': 6.966966966966967}

Epoch 7 completed!

Step 11655: {'eval_loss': 0.14804014563560486, 'eval_accuracy': 0.9214527027027027, 'eval_f1': 0.9173627154789408, 'eval_precision': 0.9677540307461567, 'eval_recall': 0.8719594594594594, 'eval_runtime': 74.2815, 'eval_samples_per_second': 79.697, 'eval_steps_per_second': 2.491, 'epoch': 7.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 8/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 11700: {'loss': 0.097069091796875, 'grad_norm': 12.462560653686523, 'learning_rate': 4.920326803774047e-06, 'epoch': 7.027027027027027}

Step 11800: {'loss': 0.09298562049865723, 'grad_norm': 5.9632391929626465, 'learning_rate': 4.7408694939716095e-06, 'epoch': 7.087087087087087}

Step 11900: {'loss': 0.09462897300720215, 'grad_norm': 9.388328552246094, 'learning_rate': 4.5637236330424005e-06, 'epoch': 7.147147147147147}

Step 12000: {'loss': 0.10114106178283691, 'grad_norm': 5.0456647872924805, 'learning_rate': 4.3889670786475195e-06, 'epoch': 7.207207207207207}

Step 12100: {'loss': 0.09757190704345703, 'grad_norm': 13.640851974487305, 'learning_rate': 4.216676638320135e-06, 'epoch': 7.267267267267267}

Step 12200: {'loss': 0.10130029678344726, 'grad_norm': 4.649428367614746, 'learning_rate': 4.0469280357076625e-06, 'epoch': 7.327327327327327}

Step 12300: {'loss': 0.09755146026611328, 'grad_norm': 10.904169082641602, 'learning_rate': 3.879795877290354e-06, 'epoch': 7.387387387387387}

Step 12400: {'loss': 0.10010345458984375, 'grad_norm': 6.663981914520264, 'learning_rate': 3.7153536195908813e-06, 'epoch': 7.4474474474474475}

Step 12500: {'loss': 0.09226519584655762, 'grad_norm': 4.197926044464111, 'learning_rate': 3.5536735368893436e-06, 'epoch': 7.5075075075075075}

Step 12600: {'loss': 0.0974037742614746, 'grad_norm': 7.5806379318237305, 'learning_rate': 3.3948266894578796e-06, 'epoch': 7.5675675675675675}

Step 12700: {'loss': 0.09198070526123046, 'grad_norm': 4.173272132873535, 'learning_rate': 3.238882892328864e-06, 'epoch': 7.627627627627628}

Step 12800: {'loss': 0.09497126579284668, 'grad_norm': 9.75599479675293, 'learning_rate': 3.085910684610374e-06, 'epoch': 7.687687687687688}

Step 12900: {'loss': 0.09356410026550294, 'grad_norm': 5.8585734367370605, 'learning_rate': 2.9359772993624635e-06, 'epoch': 7.747747747747748}

Step 13000: {'loss': 0.09091670036315919, 'grad_norm': 1.9410109519958496, 'learning_rate': 2.7891486340474683e-06, 'epoch': 7.807807807807808}

Step 13100: {'loss': 0.09584259033203125, 'grad_norm': 3.463944435119629, 'learning_rate': 2.6454892215672767e-06, 'epoch': 7.867867867867868}

Step 13200: {'loss': 0.09936676979064941, 'grad_norm': 12.28287410736084, 'learning_rate': 2.5050622019003934e-06, 'epoch': 7.927927927927928}

Step 13300: {'loss': 0.09425474166870117, 'grad_norm': 3.5267040729522705, 'learning_rate': 2.3679292943511858e-06, 'epoch': 7.987987987987988}

Epoch 8 completed!

Step 13320: {'eval_loss': 0.13899283111095428, 'eval_accuracy': 0.9255067567567568, 'eval_f1': 0.9222085023813724, 'eval_precision': 0.9649317091177556, 'eval_recall': 0.8831081081081081, 'eval_runtime': 74.3152, 'eval_samples_per_second': 79.661, 'eval_steps_per_second': 2.489, 'epoch': 8.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 9/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 13400: {'loss': 0.09344318389892578, 'grad_norm': 9.857346534729004, 'learning_rate': 2.234150770423518e-06, 'epoch': 8.048048048048049}

Step 13500: {'loss': 0.08904966354370117, 'grad_norm': 1.8633681535720825, 'learning_rate': 2.103785427330739e-06, 'epoch': 8.108108108108109}

Step 13600: {'loss': 0.08771434783935547, 'grad_norm': 7.033195972442627, 'learning_rate': 1.976890562153623e-06, 'epoch': 8.168168168168169}

Step 13700: {'loss': 0.09692730903625488, 'grad_norm': 3.9287304878234863, 'learning_rate': 1.8535219466576327e-06, 'epoch': 8.228228228228229}

Step 13800: {'loss': 0.08956248283386231, 'grad_norm': 9.55117130279541, 'learning_rate': 1.7337338027805907e-06, 'epoch': 8.288288288288289}

Step 13900: {'loss': 0.0932904052734375, 'grad_norm': 3.2342612743377686, 'learning_rate': 1.6175787788014974e-06, 'epoch': 8.348348348348349}

Step 14000: {'loss': 0.09125049591064453, 'grad_norm': 4.871983051300049, 'learning_rate': 1.505107926201007e-06, 'epoch': 8.408408408408409}

Step 14100: {'loss': 0.09426474571228027, 'grad_norm': 7.9628424644470215, 'learning_rate': 1.3963706772237161e-06, 'epoch': 8.468468468468469}

Step 14200: {'loss': 0.08759243965148926, 'grad_norm': 5.703391075134277, 'learning_rate': 1.291414823152104e-06, 'epoch': 8.528528528528529}

Step 14300: {'loss': 0.08944112777709962, 'grad_norm': 2.304861545562744, 'learning_rate': 1.19028649330172e-06, 'epoch': 8.588588588588589}

Step 14400: {'loss': 0.09100356101989746, 'grad_norm': 15.699952125549316, 'learning_rate': 1.0930301347468154e-06, 'epoch': 8.64864864864865}

Step 14500: {'loss': 0.09210302352905274, 'grad_norm': 16.08772087097168, 'learning_rate': 9.996884927853312e-07, 'epoch': 8.70870870870871}

Step 14600: {'loss': 0.09176177978515625, 'grad_norm': 5.929877758026123, 'learning_rate': 9.103025921518482e-07, 'epoch': 8.76876876876877}

Step 14700: {'loss': 0.08690542221069336, 'grad_norm': 9.338521003723145, 'learning_rate': 8.249117189867395e-07, 'epoch': 8.82882882882883}

Step 14800: {'loss': 0.09193864822387696, 'grad_norm': 2.040532350540161, 'learning_rate': 7.435534035694548e-07, 'epoch': 8.88888888888889}

Step 14900: {'loss': 0.08785438537597656, 'grad_norm': 1.6640229225158691, 'learning_rate': 6.662634038235328e-07, 'epoch': 8.94894894894895}

Epoch 9 completed!

Step 14985: {'eval_loss': 0.12831133604049683, 'eval_accuracy': 0.9280405405405405, 'eval_f1': 0.9260159777700591, 'eval_precision': 0.9528234453180844, 'eval_recall': 0.9006756756756756, 'eval_runtime': 74.3448, 'eval_samples_per_second': 79.629, 'eval_steps_per_second': 2.488, 'epoch': 9.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 10/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 15000: {'loss': 0.09223934173583985, 'grad_norm': 2.553166627883911, 'learning_rate': 5.930756896005707e-07, 'epoch': 9.00900900900901}

Step 15100: {'loss': 0.08792598724365235, 'grad_norm': 5.609703063964844, 'learning_rate': 5.240224277500827e-07, 'epoch': 9.06906906906907}

Step 15200: {'loss': 0.08754097938537597, 'grad_norm': 5.392386436462402, 'learning_rate': 4.591339679818041e-07, 'epoch': 9.12912912912913}

Step 15300: {'loss': 0.08540244102478027, 'grad_norm': 3.6613667011260986, 'learning_rate': 3.984388295266284e-07, 'epoch': 9.18918918918919}

Step 15400: {'loss': 0.09434209823608398, 'grad_norm': 8.08298110961914, 'learning_rate': 3.4196368860208495e-07, 'epoch': 9.24924924924925}

Step 15500: {'loss': 0.08806011199951172, 'grad_norm': 7.80902099609375, 'learning_rate': 2.897333666878299e-07, 'epoch': 9.30930930930931}

Step 15600: {'loss': 0.09116567611694336, 'grad_norm': 3.48943829536438, 'learning_rate': 2.4177081961631264e-07, 'epoch': 9.36936936936937}

Step 15700: {'loss': 0.09161018371582032, 'grad_norm': 6.606525897979736, 'learning_rate': 1.980971274834287e-07, 'epoch': 9.42942942942943}

Step 15800: {'loss': 0.09060593605041505, 'grad_norm': 2.8500523567199707, 'learning_rate': 1.5873148538356752e-07, 'epoch': 9.48948948948949}

Step 15900: {'loss': 0.09121838569641114, 'grad_norm': 3.3488001823425293, 'learning_rate': 1.2369119497314674e-07, 'epoch': 9.54954954954955}

Step 16000: {'loss': 0.08856124877929687, 'grad_norm': 1.5175331830978394, 'learning_rate': 9.299165686633471e-08, 'epoch': 9.60960960960961}

Step 16100: {'loss': 0.08564473152160644, 'grad_norm': 5.019875526428223, 'learning_rate': 6.664636386630286e-08, 'epoch': 9.66966966966967}

Step 16200: {'loss': 0.0893911075592041, 'grad_norm': 5.030637741088867, 'learning_rate': 4.466689503498045e-08, 'epoch': 9.72972972972973}

Step 16300: {'loss': 0.07997216701507569, 'grad_norm': 5.903461456298828, 'learning_rate': 2.7062910603921078e-08, 'epoch': 9.78978978978979}

Step 16400: {'loss': 0.08873888969421387, 'grad_norm': 7.776242256164551, 'learning_rate': 1.3842147728522215e-08, 'epoch': 9.84984984984985}

Step 16500: {'loss': 0.08587578773498535, 'grad_norm': 0.8870857357978821, 'learning_rate': 5.010417087452091e-09, 'epoch': 9.90990990990991}

Step 16600: {'loss': 0.08834776878356934, 'grad_norm': 2.106698989868164, 'learning_rate': 5.716003287936645e-10, 'epoch': 9.96996996996997}

Epoch 10 completed!

Step 16650: {'eval_loss': 0.12748399376869202, 'eval_accuracy': 0.9288851351351352, 'eval_f1': 0.9269477702585459, 'eval_precision': 0.9529075990010702, 'eval_recall': 0.9023648648648649, 'eval_runtime': 74.197, 'eval_samples_per_second': 79.788, 'eval_steps_per_second': 2.493, 'epoch': 10.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 16650: {'train_runtime': 10766.1548, 'train_samples_per_second': 49.485, 'train_steps_per_second': 1.547, 'total_flos': 2.7757476441072e+16, 'train_loss': 0.17919572523764304, 'epoch': 10.0}

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 16650: {'eval_loss': 0.12748399376869202, 'eval_accuracy': 0.9288851351351352, 'eval_f1': 0.9269477702585459, 'eval_precision': 0.9529075990010702, 'eval_recall': 0.9023648648648649, 'eval_runtime': 74.2101, 'eval_samples_per_second': 79.774, 'eval_steps_per_second': 2.493, 'epoch': 10.0}

--- 4-Layer-Standard_a0.3_t5.0 Results ---
  Accuracy:  92.89%
  F1 Score:  0.9269
  Precision: 0.9529
  Recall:    0.9024
  Loss:      0.1275
  Time:      179.4 min

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Results saved (7 total)

######################################################################
# Run 4/4: 4-Layer-Standard | alpha=0.5 | temp=1.0
######################################################################

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Student parameters: 32,485,634 (32.5M)

Starting training...

============================================================

Starting Epoch 1/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 100: {'loss': 0.5680720901489258, 'grad_norm': 3.3201661109924316, 'learning_rate': 1.1891891891891893e-06, 'epoch': 0.06006006006006006}

Step 200: {'loss': 0.5523629760742188, 'grad_norm': 4.71054744720459, 'learning_rate': 2.3903903903903904e-06, 'epoch': 0.12012012012012012}

Step 300: {'loss': 0.5468696975708007, 'grad_norm': 2.0938720703125, 'learning_rate': 3.5915915915915917e-06, 'epoch': 0.18018018018018017}

Step 400: {'loss': 0.5412183380126954, 'grad_norm': 4.799228191375732, 'learning_rate': 4.792792792792793e-06, 'epoch': 0.24024024024024024}

Step 500: {'loss': 0.5342352294921875, 'grad_norm': 5.274362087249756, 'learning_rate': 5.993993993993994e-06, 'epoch': 0.3003003003003003}

Step 600: {'loss': 0.5061968612670898, 'grad_norm': 7.7165350914001465, 'learning_rate': 7.195195195195196e-06, 'epoch': 0.36036036036036034}

Step 700: {'loss': 0.4164238739013672, 'grad_norm': 6.62201452255249, 'learning_rate': 8.396396396396397e-06, 'epoch': 0.42042042042042044}

Step 800: {'loss': 0.3398405838012695, 'grad_norm': 19.4160099029541, 'learning_rate': 9.597597597597599e-06, 'epoch': 0.4804804804804805}

Step 900: {'loss': 0.3118495750427246, 'grad_norm': 17.36487579345703, 'learning_rate': 1.07987987987988e-05, 'epoch': 0.5405405405405406}

Step 1000: {'loss': 0.2974247932434082, 'grad_norm': 29.40660285949707, 'learning_rate': 1.2e-05, 'epoch': 0.6006006006006006}

Step 1100: {'loss': 0.28325428009033204, 'grad_norm': 26.79983139038086, 'learning_rate': 1.3201201201201202e-05, 'epoch': 0.6606606606606606}

Step 1200: {'loss': 0.30484987258911134, 'grad_norm': 13.29457950592041, 'learning_rate': 1.4402402402402404e-05, 'epoch': 0.7207207207207207}

Step 1300: {'loss': 0.26107326507568357, 'grad_norm': 19.567888259887695, 'learning_rate': 1.5603603603603605e-05, 'epoch': 0.7807807807807807}

Step 1400: {'loss': 0.2766719436645508, 'grad_norm': 8.25919246673584, 'learning_rate': 1.6804804804804807e-05, 'epoch': 0.8408408408408409}

Step 1500: {'loss': 0.2989120101928711, 'grad_norm': 1.991196632385254, 'learning_rate': 1.8006006006006005e-05, 'epoch': 0.9009009009009009}

Step 1600: {'loss': 0.260336799621582, 'grad_norm': 37.80255126953125, 'learning_rate': 1.9207207207207207e-05, 'epoch': 0.960960960960961}

Epoch 1 completed!

Step 1665: {'eval_loss': 0.2576175034046173, 'eval_accuracy': 0.8474662162162162, 'eval_f1': 0.8587959343236904, 'eval_precision': 0.7994177583697234, 'eval_recall': 0.9277027027027027, 'eval_runtime': 74.2251, 'eval_samples_per_second': 79.757, 'eval_steps_per_second': 2.492, 'epoch': 1.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 2/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 1700: {'loss': 0.28510494232177735, 'grad_norm': 37.15465545654297, 'learning_rate': 1.9999745954064855e-05, 'epoch': 1.021021021021021}

Step 1800: {'loss': 0.26417423248291017, 'grad_norm': 74.14482879638672, 'learning_rate': 1.9996054179825038e-05, 'epoch': 1.0810810810810811}

Step 1900: {'loss': 0.24324399948120118, 'grad_norm': 30.808406829833984, 'learning_rate': 1.998796902380012e-05, 'epoch': 1.1411411411411412}

Step 2000: {'loss': 0.2386520767211914, 'grad_norm': 8.669174194335938, 'learning_rate': 1.997549403950997e-05, 'epoch': 1.2012012012012012}

Step 2100: {'loss': 0.2531046485900879, 'grad_norm': 40.98461151123047, 'learning_rate': 1.995863470985492e-05, 'epoch': 1.2612612612612613}

Step 2200: {'loss': 0.23924570083618163, 'grad_norm': 33.71818161010742, 'learning_rate': 1.9937398444705953e-05, 'epoch': 1.3213213213213213}

Step 2300: {'loss': 0.24046993255615234, 'grad_norm': 23.014087677001953, 'learning_rate': 1.991179457764798e-05, 'epoch': 1.3813813813813813}

Step 2400: {'loss': 0.22854328155517578, 'grad_norm': 19.816192626953125, 'learning_rate': 1.988183436187763e-05, 'epoch': 1.4414414414414414}

Step 2500: {'loss': 0.244999942779541, 'grad_norm': 7.890929222106934, 'learning_rate': 1.9847530965257328e-05, 'epoch': 1.5015015015015014}

Step 2600: {'loss': 0.2440909767150879, 'grad_norm': 13.053106307983398, 'learning_rate': 1.9808899464527874e-05, 'epoch': 1.5615615615615615}

Step 2700: {'loss': 0.21410425186157225, 'grad_norm': 9.497718811035156, 'learning_rate': 1.9765956838682032e-05, 'epoch': 1.6216216216216215}

Step 2800: {'loss': 0.21433340072631835, 'grad_norm': 5.409353733062744, 'learning_rate': 1.971872196150208e-05, 'epoch': 1.6816816816816815}

Step 2900: {'loss': 0.2233233070373535, 'grad_norm': 27.667144775390625, 'learning_rate': 1.9667215593264558e-05, 'epoch': 1.7417417417417418}

Step 3000: {'loss': 0.2327095413208008, 'grad_norm': 27.119962692260742, 'learning_rate': 1.9611460371615865e-05, 'epoch': 1.8018018018018018}

Step 3100: {'loss': 0.21421459197998047, 'grad_norm': 4.885706901550293, 'learning_rate': 1.955148080162279e-05, 'epoch': 1.8618618618618619}

Step 3200: {'loss': 0.23505512237548828, 'grad_norm': 35.54082489013672, 'learning_rate': 1.9487303245002217e-05, 'epoch': 1.921921921921922}

Step 3300: {'loss': 0.21187837600708007, 'grad_norm': 8.078475952148438, 'learning_rate': 1.9418955908534863e-05, 'epoch': 1.981981981981982}

Epoch 2 completed!

Step 3330: {'eval_loss': 0.1956152766942978, 'eval_accuracy': 0.8883445945945946, 'eval_f1': 0.8896309901486058, 'eval_precision': 0.8794981842192142, 'eval_recall': 0.9, 'eval_runtime': 74.333, 'eval_samples_per_second': 79.642, 'eval_steps_per_second': 2.489, 'epoch': 2.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 3/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 3400: {'loss': 0.2199386787414551, 'grad_norm': 24.893333435058594, 'learning_rate': 1.9346468831668065e-05, 'epoch': 2.042042042042042}

Step 3500: {'loss': 0.1975444221496582, 'grad_norm': 8.906455993652344, 'learning_rate': 1.926987387331309e-05, 'epoch': 2.1021021021021022}

Step 3600: {'loss': 0.18399042129516602, 'grad_norm': 44.8929328918457, 'learning_rate': 1.918920469784278e-05, 'epoch': 2.1621621621621623}

Step 3700: {'loss': 0.19832717895507812, 'grad_norm': 2.603306531906128, 'learning_rate': 1.9104496760295675e-05, 'epoch': 2.2222222222222223}

Step 3800: {'loss': 0.19731964111328126, 'grad_norm': 14.045291900634766, 'learning_rate': 1.9015787290793092e-05, 'epoch': 2.2822822822822824}

Step 3900: {'loss': 0.20076778411865234, 'grad_norm': 41.49172592163086, 'learning_rate': 1.892311527817608e-05, 'epoch': 2.3423423423423424}

Step 4000: {'loss': 0.19193147659301757, 'grad_norm': 9.385049819946289, 'learning_rate': 1.8826521452869348e-05, 'epoch': 2.4024024024024024}

Step 4100: {'loss': 0.20628934860229492, 'grad_norm': 30.184568405151367, 'learning_rate': 1.872604826897979e-05, 'epoch': 2.4624624624624625}

Step 4200: {'loss': 0.18555604934692382, 'grad_norm': 1.7603102922439575, 'learning_rate': 1.8621739885637407e-05, 'epoch': 2.5225225225225225}

Step 4300: {'loss': 0.20618679046630858, 'grad_norm': 41.004127502441406, 'learning_rate': 1.8513642147586855e-05, 'epoch': 2.5825825825825826}

Step 4400: {'loss': 0.1926654815673828, 'grad_norm': 20.558889389038086, 'learning_rate': 1.8401802565038135e-05, 'epoch': 2.6426426426426426}

Step 4500: {'loss': 0.1822141456604004, 'grad_norm': 19.412017822265625, 'learning_rate': 1.8286270292785337e-05, 'epoch': 2.7027027027027026}

Step 4600: {'loss': 0.18936002731323243, 'grad_norm': 24.721817016601562, 'learning_rate': 1.81670961086025e-05, 'epoch': 2.7627627627627627}

Step 4700: {'loss': 0.192158203125, 'grad_norm': 14.363872528076172, 'learning_rate': 1.8044332390926224e-05, 'epoch': 2.8228228228228227}

Step 4800: {'loss': 0.20707424163818358, 'grad_norm': 4.725065231323242, 'learning_rate': 1.7918033095834714e-05, 'epoch': 2.8828828828828827}

Step 4900: {'loss': 0.18920822143554689, 'grad_norm': 1.8454207181930542, 'learning_rate': 1.778825373333347e-05, 'epoch': 2.942942942942943}

Epoch 3 completed!

Step 4995: {'eval_loss': 0.3638482093811035, 'eval_accuracy': 0.8006756756756757, 'eval_f1': 0.7537562604340567, 'eval_precision': 0.9858078602620087, 'eval_recall': 0.6101351351351352, 'eval_runtime': 74.2187, 'eval_samples_per_second': 79.764, 'eval_steps_per_second': 2.493, 'epoch': 3.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 4/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 5000: {'loss': 0.18356245040893554, 'grad_norm': 5.257236480712891, 'learning_rate': 1.7655051342958005e-05, 'epoch': 3.003003003003003}

Step 5100: {'loss': 0.17527896881103516, 'grad_norm': 12.33814811706543, 'learning_rate': 1.7518484468704283e-05, 'epoch': 3.063063063063063}

Step 5200: {'loss': 0.17695161819458008, 'grad_norm': 6.645777225494385, 'learning_rate': 1.7378613133297974e-05, 'epoch': 3.123123123123123}

Step 5300: {'loss': 0.17677242279052735, 'grad_norm': 2.223836660385132, 'learning_rate': 1.7235498811813757e-05, 'epoch': 3.1831831831831834}

Step 5400: {'loss': 0.18022748947143555, 'grad_norm': 5.976917266845703, 'learning_rate': 1.708920440465632e-05, 'epoch': 3.2432432432432434}

Step 5500: {'loss': 0.17780256271362305, 'grad_norm': 2.5674617290496826, 'learning_rate': 1.6939794209914907e-05, 'epoch': 3.3033033033033035}

Step 5600: {'loss': 0.1659027099609375, 'grad_norm': 23.525447845458984, 'learning_rate': 1.6787333895103535e-05, 'epoch': 3.3633633633633635}

Step 5700: {'loss': 0.16677017211914064, 'grad_norm': 12.376837730407715, 'learning_rate': 1.6631890468299402e-05, 'epoch': 3.4234234234234235}

Step 5800: {'loss': 0.18299114227294921, 'grad_norm': 24.334009170532227, 'learning_rate': 1.6473532248692016e-05, 'epoch': 3.4834834834834836}

Step 5900: {'loss': 0.18063629150390625, 'grad_norm': 26.840925216674805, 'learning_rate': 1.6312328836556152e-05, 'epoch': 3.5435435435435436}

Step 6000: {'loss': 0.16917675018310546, 'grad_norm': 3.967174768447876, 'learning_rate': 1.6148351082661707e-05, 'epoch': 3.6036036036036037}

Step 6100: {'loss': 0.17804607391357422, 'grad_norm': 16.792245864868164, 'learning_rate': 1.5981671057133975e-05, 'epoch': 3.6636636636636637}

Step 6200: {'loss': 0.1598211097717285, 'grad_norm': 13.742695808410645, 'learning_rate': 1.5812362017777965e-05, 'epoch': 3.7237237237237237}

Step 6300: {'loss': 0.17128557205200196, 'grad_norm': 15.920195579528809, 'learning_rate': 1.564049837788079e-05, 'epoch': 3.7837837837837838}

Step 6400: {'loss': 0.16436946868896485, 'grad_norm': 9.06403636932373, 'learning_rate': 1.546615567350612e-05, 'epoch': 3.843843843843844}

Step 6500: {'loss': 0.16239225387573242, 'grad_norm': 5.6946492195129395, 'learning_rate': 1.5289410530295233e-05, 'epoch': 3.903903903903904}

Step 6600: {'loss': 0.15650080680847167, 'grad_norm': 6.632956504821777, 'learning_rate': 1.5110340629789148e-05, 'epoch': 3.963963963963964}

Epoch 4 completed!

Step 6660: {'eval_loss': 0.1696951985359192, 'eval_accuracy': 0.9045608108108109, 'eval_f1': 0.9005806792187225, 'eval_precision': 0.9397723099522586, 'eval_recall': 0.864527027027027, 'eval_runtime': 74.3272, 'eval_samples_per_second': 79.648, 'eval_steps_per_second': 2.489, 'epoch': 4.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 5/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 6700: {'loss': 0.1565522289276123, 'grad_norm': 21.503225326538086, 'learning_rate': 1.4929024675286688e-05, 'epoch': 4.024024024024024}

Step 6800: {'loss': 0.134188756942749, 'grad_norm': 20.621227264404297, 'learning_rate': 1.4745542357253462e-05, 'epoch': 4.084084084084084}

Step 6900: {'loss': 0.14577125549316405, 'grad_norm': 5.575345993041992, 'learning_rate': 1.4559974318296984e-05, 'epoch': 4.1441441441441444}

Step 7000: {'loss': 0.14751776695251465, 'grad_norm': 7.84670877456665, 'learning_rate': 1.4372402117723314e-05, 'epoch': 4.2042042042042045}

Step 7100: {'loss': 0.14294946670532227, 'grad_norm': 8.651793479919434, 'learning_rate': 1.4182908195690799e-05, 'epoch': 4.2642642642642645}

Step 7200: {'loss': 0.1418583869934082, 'grad_norm': 10.593796730041504, 'learning_rate': 1.399157583697666e-05, 'epoch': 4.324324324324325}

Step 7300: {'loss': 0.14158342361450196, 'grad_norm': 12.087706565856934, 'learning_rate': 1.3798489134372361e-05, 'epoch': 4.384384384384385}

Step 7400: {'loss': 0.14173320770263673, 'grad_norm': 13.627060890197754, 'learning_rate': 1.3603732951723874e-05, 'epoch': 4.444444444444445}

Step 7500: {'loss': 0.13383769989013672, 'grad_norm': 3.2767724990844727, 'learning_rate': 1.3407392886633008e-05, 'epoch': 4.504504504504505}

Step 7600: {'loss': 0.14837053298950195, 'grad_norm': 3.8530027866363525, 'learning_rate': 1.3209555232836284e-05, 'epoch': 4.564564564564565}

Step 7700: {'loss': 0.1381542205810547, 'grad_norm': 32.7409782409668, 'learning_rate': 1.301030694227784e-05, 'epoch': 4.624624624624625}

Step 7800: {'loss': 0.1368832778930664, 'grad_norm': 4.892219066619873, 'learning_rate': 1.2809735586893028e-05, 'epoch': 4.684684684684685}

Step 7900: {'loss': 0.13710330963134765, 'grad_norm': 4.293463706970215, 'learning_rate': 1.2607929320119547e-05, 'epoch': 4.744744744744745}

Step 8000: {'loss': 0.14299528121948243, 'grad_norm': 5.06033182144165, 'learning_rate': 1.2404976838152977e-05, 'epoch': 4.804804804804805}

Step 8100: {'loss': 0.13766730308532715, 'grad_norm': 11.505378723144531, 'learning_rate': 1.2200967340963774e-05, 'epoch': 4.864864864864865}

Step 8200: {'loss': 0.12756553649902344, 'grad_norm': 1.9488860368728638, 'learning_rate': 1.1995990493092849e-05, 'epoch': 4.924924924924925}

Step 8300: {'loss': 0.13396947860717773, 'grad_norm': 3.1353065967559814, 'learning_rate': 1.1790136384242957e-05, 'epoch': 4.984984984984985}

Epoch 5 completed!

Step 8325: {'eval_loss': 0.1504305899143219, 'eval_accuracy': 0.9150337837837837, 'eval_f1': 0.9122010822133008, 'eval_precision': 0.9436619718309859, 'eval_recall': 0.8827702702702702, 'eval_runtime': 74.4673, 'eval_samples_per_second': 79.498, 'eval_steps_per_second': 2.484, 'epoch': 5.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 6/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 8400: {'loss': 0.1180638885498047, 'grad_norm': 5.875917434692383, 'learning_rate': 1.158349548968323e-05, 'epoch': 5.045045045045045}

Step 8500: {'loss': 0.10809466361999512, 'grad_norm': 8.994190216064453, 'learning_rate': 1.1376158630484258e-05, 'epoch': 5.105105105105105}

Step 8600: {'loss': 0.1133708667755127, 'grad_norm': 18.85939598083496, 'learning_rate': 1.116821693360115e-05, 'epoch': 5.165165165165165}

Step 8700: {'loss': 0.13454371452331543, 'grad_norm': 4.558155536651611, 'learning_rate': 1.0959761791822208e-05, 'epoch': 5.225225225225225}

Step 8800: {'loss': 0.11563897132873535, 'grad_norm': 6.281035900115967, 'learning_rate': 1.0750884823600713e-05, 'epoch': 5.285285285285285}

Step 8900: {'loss': 0.11894618988037109, 'grad_norm': 5.0955915451049805, 'learning_rate': 1.0541677832787569e-05, 'epoch': 5.345345345345345}

Step 9000: {'loss': 0.12653611183166505, 'grad_norm': 7.351639270782471, 'learning_rate': 1.0332232768282429e-05, 'epoch': 5.405405405405405}

Step 9100: {'loss': 0.11647591590881348, 'grad_norm': 15.165822982788086, 'learning_rate': 1.0122641683621102e-05, 'epoch': 5.465465465465465}

Step 9200: {'loss': 0.11978825569152832, 'grad_norm': 3.913377285003662, 'learning_rate': 9.912996696516946e-06, 'epoch': 5.525525525525525}

Step 9300: {'loss': 0.1200046730041504, 'grad_norm': 1.7287206649780273, 'learning_rate': 9.703389948374077e-06, 'epoch': 5.585585585585585}

Step 9400: {'loss': 0.1194012451171875, 'grad_norm': 4.874820232391357, 'learning_rate': 9.493913563790135e-06, 'epoch': 5.645645645645645}

Step 9500: {'loss': 0.11487861633300782, 'grad_norm': 16.384721755981445, 'learning_rate': 9.28465961006646e-06, 'epoch': 5.7057057057057055}

Step 9600: {'loss': 0.11769705772399902, 'grad_norm': 8.102749824523926, 'learning_rate': 9.07572005674346e-06, 'epoch': 5.7657657657657655}

Step 9700: {'loss': 0.11707388877868652, 'grad_norm': 17.042078018188477, 'learning_rate': 8.867186735178911e-06, 'epoch': 5.8258258258258255}

Step 9800: {'loss': 0.11591188430786133, 'grad_norm': 1.3897359371185303, 'learning_rate': 8.659151298187018e-06, 'epoch': 5.885885885885886}

Step 9900: {'loss': 0.12142786979675294, 'grad_norm': 9.559808731079102, 'learning_rate': 8.451705179755947e-06, 'epoch': 5.945945945945946}

Epoch 6 completed!

Step 9990: {'eval_loss': 0.14468224346637726, 'eval_accuracy': 0.9217905405405405, 'eval_f1': 0.9210571184995737, 'eval_precision': 0.929776247848537, 'eval_recall': 0.9125, 'eval_runtime': 74.386, 'eval_samples_per_second': 79.585, 'eval_steps_per_second': 2.487, 'epoch': 6.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 7/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 10000: {'loss': 0.11837778091430665, 'grad_norm': 9.518370628356934, 'learning_rate': 8.244939554861512e-06, 'epoch': 6.006006006006006}

Step 10100: {'loss': 0.1075743293762207, 'grad_norm': 12.68069076538086, 'learning_rate': 8.038945299394722e-06, 'epoch': 6.066066066066066}

Step 10200: {'loss': 0.10760154724121093, 'grad_norm': 11.32813549041748, 'learning_rate': 7.833812950220783e-06, 'epoch': 6.126126126126126}

Step 10300: {'loss': 0.11099950790405273, 'grad_norm': 1.978031039237976, 'learning_rate': 7.62963266538707e-06, 'epoch': 6.186186186186186}

Step 10400: {'loss': 0.11127508163452149, 'grad_norm': 11.758615493774414, 'learning_rate': 7.426494184497655e-06, 'epoch': 6.246246246246246}

Step 10500: {'loss': 0.11122533798217774, 'grad_norm': 2.6761224269866943, 'learning_rate': 7.224486789271671e-06, 'epoch': 6.306306306306306}

Step 10600: {'loss': 0.10714216232299804, 'grad_norm': 6.092061519622803, 'learning_rate': 7.0236992643029854e-06, 'epoch': 6.366366366366367}

Step 10700: {'loss': 0.10184981346130371, 'grad_norm': 5.741934299468994, 'learning_rate': 6.824219858038339e-06, 'epoch': 6.426426426426427}

Step 10800: {'loss': 0.10257491111755371, 'grad_norm': 11.645792961120605, 'learning_rate': 6.626136243991124e-06, 'epoch': 6.486486486486487}

Step 10900: {'loss': 0.10565423965454102, 'grad_norm': 2.5279581546783447, 'learning_rate': 6.429535482207847e-06, 'epoch': 6.546546546546547}

Step 11000: {'loss': 0.10917920112609864, 'grad_norm': 17.89603614807129, 'learning_rate': 6.234503981004265e-06, 'epoch': 6.606606606606607}

Step 11100: {'loss': 0.11373817443847656, 'grad_norm': 6.147568702697754, 'learning_rate': 6.0411274589878834e-06, 'epoch': 6.666666666666667}

Step 11200: {'loss': 0.114996976852417, 'grad_norm': 6.743732929229736, 'learning_rate': 5.849490907383659e-06, 'epoch': 6.726726726726727}

Step 11300: {'loss': 0.1111478328704834, 'grad_norm': 19.252147674560547, 'learning_rate': 5.659678552679371e-06, 'epoch': 6.786786786786787}

Step 11400: {'loss': 0.10149419784545899, 'grad_norm': 2.395402193069458, 'learning_rate': 5.471773819607095e-06, 'epoch': 6.846846846846847}

Step 11500: {'loss': 0.10635011672973632, 'grad_norm': 6.518404960632324, 'learning_rate': 5.285859294477054e-06, 'epoch': 6.906906906906907}

Step 11600: {'loss': 0.10574614524841308, 'grad_norm': 6.63862943649292, 'learning_rate': 5.102016688880014e-06, 'epoch': 6.966966966966967}

Epoch 7 completed!

Step 11655: {'eval_loss': 0.16127227246761322, 'eval_accuracy': 0.9158783783783784, 'eval_f1': 0.9107846649946256, 'eval_precision': 0.969488939740656, 'eval_recall': 0.8587837837837838, 'eval_runtime': 74.4156, 'eval_samples_per_second': 79.553, 'eval_steps_per_second': 2.486, 'epoch': 7.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 8/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 11700: {'loss': 0.10224444389343262, 'grad_norm': 1.4941424131393433, 'learning_rate': 4.920326803774047e-06, 'epoch': 7.027027027027027}

Step 11800: {'loss': 0.09877606391906739, 'grad_norm': 4.295195579528809, 'learning_rate': 4.7408694939716095e-06, 'epoch': 7.087087087087087}

Step 11900: {'loss': 0.0971732234954834, 'grad_norm': 9.346358299255371, 'learning_rate': 4.5637236330424005e-06, 'epoch': 7.147147147147147}

Step 12000: {'loss': 0.1047370433807373, 'grad_norm': 5.140501022338867, 'learning_rate': 4.3889670786475195e-06, 'epoch': 7.207207207207207}

Step 12100: {'loss': 0.0973523998260498, 'grad_norm': 10.867860794067383, 'learning_rate': 4.216676638320135e-06, 'epoch': 7.267267267267267}

Step 12200: {'loss': 0.10427671432495117, 'grad_norm': 2.4616055488586426, 'learning_rate': 4.0469280357076625e-06, 'epoch': 7.327327327327327}

Step 12300: {'loss': 0.09901340484619141, 'grad_norm': 13.118523597717285, 'learning_rate': 3.879795877290354e-06, 'epoch': 7.387387387387387}

Step 12400: {'loss': 0.10062320709228516, 'grad_norm': 13.131733894348145, 'learning_rate': 3.7153536195908813e-06, 'epoch': 7.4474474474474475}

Step 12500: {'loss': 0.09475646018981934, 'grad_norm': 4.8589982986450195, 'learning_rate': 3.5536735368893436e-06, 'epoch': 7.5075075075075075}

Step 12600: {'loss': 0.10116595268249512, 'grad_norm': 13.21198844909668, 'learning_rate': 3.3948266894578796e-06, 'epoch': 7.5675675675675675}

Step 12700: {'loss': 0.09430856704711914, 'grad_norm': 7.985689640045166, 'learning_rate': 3.238882892328864e-06, 'epoch': 7.627627627627628}

Step 12800: {'loss': 0.09904269218444824, 'grad_norm': 9.37354850769043, 'learning_rate': 3.085910684610374e-06, 'epoch': 7.687687687687688}

Step 12900: {'loss': 0.09807177543640137, 'grad_norm': 8.884196281433105, 'learning_rate': 2.9359772993624635e-06, 'epoch': 7.747747747747748}

Step 13000: {'loss': 0.092959566116333, 'grad_norm': 2.1450510025024414, 'learning_rate': 2.7891486340474683e-06, 'epoch': 7.807807807807808}

Step 13100: {'loss': 0.09946157455444336, 'grad_norm': 4.641994953155518, 'learning_rate': 2.6454892215672767e-06, 'epoch': 7.867867867867868}

Step 13200: {'loss': 0.09933591842651367, 'grad_norm': 19.732027053833008, 'learning_rate': 2.5050622019003934e-06, 'epoch': 7.927927927927928}

Step 13300: {'loss': 0.09599769592285157, 'grad_norm': 1.981613278388977, 'learning_rate': 2.3679292943511858e-06, 'epoch': 7.987987987987988}

Epoch 8 completed!

Step 13320: {'eval_loss': 0.1522461622953415, 'eval_accuracy': 0.9204391891891892, 'eval_f1': 0.9168285361116016, 'eval_precision': 0.9604143544210136, 'eval_recall': 0.8770270270270271, 'eval_runtime': 74.2246, 'eval_samples_per_second': 79.758, 'eval_steps_per_second': 2.492, 'epoch': 8.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 9/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 13400: {'loss': 0.09461532592773438, 'grad_norm': 13.590677261352539, 'learning_rate': 2.234150770423518e-06, 'epoch': 8.048048048048049}

Step 13500: {'loss': 0.09131092071533203, 'grad_norm': 4.189836025238037, 'learning_rate': 2.103785427330739e-06, 'epoch': 8.108108108108109}

Step 13600: {'loss': 0.08667056083679199, 'grad_norm': 5.438859462738037, 'learning_rate': 1.976890562153623e-06, 'epoch': 8.168168168168169}

Step 13700: {'loss': 0.10437875747680664, 'grad_norm': 8.44603443145752, 'learning_rate': 1.8535219466576327e-06, 'epoch': 8.228228228228229}

Step 13800: {'loss': 0.09084632873535156, 'grad_norm': 13.19965934753418, 'learning_rate': 1.7337338027805907e-06, 'epoch': 8.288288288288289}

Step 13900: {'loss': 0.09808675765991211, 'grad_norm': 5.923699855804443, 'learning_rate': 1.6175787788014974e-06, 'epoch': 8.348348348348349}

Step 14000: {'loss': 0.09220224380493164, 'grad_norm': 7.092413425445557, 'learning_rate': 1.505107926201007e-06, 'epoch': 8.408408408408409}

Step 14100: {'loss': 0.09655593872070313, 'grad_norm': 3.560715913772583, 'learning_rate': 1.3963706772237161e-06, 'epoch': 8.468468468468469}

Step 14200: {'loss': 0.08713394165039062, 'grad_norm': 5.304557800292969, 'learning_rate': 1.291414823152104e-06, 'epoch': 8.528528528528529}

Step 14300: {'loss': 0.09181406021118164, 'grad_norm': 8.811511039733887, 'learning_rate': 1.19028649330172e-06, 'epoch': 8.588588588588589}

Step 14400: {'loss': 0.09271754264831543, 'grad_norm': 11.454588890075684, 'learning_rate': 1.0930301347468154e-06, 'epoch': 8.64864864864865}

Step 14500: {'loss': 0.09528163909912109, 'grad_norm': 11.431264877319336, 'learning_rate': 9.996884927853312e-07, 'epoch': 8.70870870870871}

Step 14600: {'loss': 0.09440337181091309, 'grad_norm': 3.6517786979675293, 'learning_rate': 9.103025921518482e-07, 'epoch': 8.76876876876877}

Step 14700: {'loss': 0.08529273986816406, 'grad_norm': 6.703122138977051, 'learning_rate': 8.249117189867395e-07, 'epoch': 8.82882882882883}

Step 14800: {'loss': 0.09630274772644043, 'grad_norm': 2.0319929122924805, 'learning_rate': 7.435534035694548e-07, 'epoch': 8.88888888888889}

Step 14900: {'loss': 0.08936685562133789, 'grad_norm': 8.012117385864258, 'learning_rate': 6.662634038235328e-07, 'epoch': 8.94894894894895}

Epoch 9 completed!

Step 14985: {'eval_loss': 0.14203345775604248, 'eval_accuracy': 0.925168918918919, 'eval_f1': 0.9232900432900433, 'eval_precision': 0.9470692717584369, 'eval_recall': 0.9006756756756756, 'eval_runtime': 73.9341, 'eval_samples_per_second': 80.071, 'eval_steps_per_second': 2.502, 'epoch': 9.0}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================

Starting Epoch 10/10

============================================================

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Step 15000: {'loss': 0.09536660194396973, 'grad_norm': 5.407572269439697, 'learning_rate': 5.930756896005707e-07, 'epoch': 9.00900900900901}

Step 15100: {'loss': 0.08730847358703614, 'grad_norm': 2.693438768386841, 'learning_rate': 5.240224277500827e-07, 'epoch': 9.06906906906907}

Step 15200: {'loss': 0.08742190361022949, 'grad_norm': 6.514116287231445, 'learning_rate': 4.591339679818041e-07, 'epoch': 9.12912912912913}

Step 15300: {'loss': 0.08369611740112305, 'grad_norm': 9.476940155029297, 'learning_rate': 3.984388295266284e-07, 'epoch': 9.18918918918919}

Step 15400: {'loss': 0.09494920730590821, 'grad_norm': 10.828990936279297, 'learning_rate': 3.4196368860208495e-07, 'epoch': 9.24924924924925}

Step 15500: {'loss': 0.08755021095275879, 'grad_norm': 6.911221504211426, 'learning_rate': 2.897333666878299e-07, 'epoch': 9.30930930930931}

Step 15600: {'loss': 0.09411685943603515, 'grad_norm': 4.0132060050964355, 'learning_rate': 2.4177081961631264e-07, 'epoch': 9.36936936936937}

Step 15700: {'loss': 0.09480953216552734, 'grad_norm': 5.307687282562256, 'learning_rate': 1.980971274834287e-07, 'epoch': 9.42942942942943}

Step 15800: {'loss': 0.09072054862976074, 'grad_norm': 4.575117111206055, 'learning_rate': 1.5873148538356752e-07, 'epoch': 9.48948948948949}

Step 15900: {'loss': 0.0927049732208252, 'grad_norm': 7.841446399688721, 'learning_rate': 1.2369119497314674e-07, 'epoch': 9.54954954954955}

Step 16000: {'loss': 0.09022007942199707, 'grad_norm': 3.289018154144287, 'learning_rate': 9.299165686633471e-08, 'epoch': 9.60960960960961}

Step 16100: {'loss': 0.08908653259277344, 'grad_norm': 5.43095588684082, 'learning_rate': 6.664636386630286e-08, 'epoch': 9.66966966966967}

Step 16200: {'loss': 0.09188619613647461, 'grad_norm': 4.740228176116943, 'learning_rate': 4.466689503498045e-08, 'epoch': 9.72972972972973}

Step 16300: {'loss': 0.08053483009338379, 'grad_norm': 7.39125919342041, 'learning_rate': 2.7062910603921078e-08, 'epoch': 9.78978978978979}

Step 16400: {'loss': 0.08986308097839356, 'grad_norm': 8.240013122558594, 'learning_rate': 1.3842147728522215e-08, 'epoch': 9.84984984984985}

# Results Summary & Visualization

In [ ]:
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd

TEACHER_ACCURACY = 0.9671

# ===== FULL RESULTS TABLE =====
print("="*110)
print("KNOWLEDGE DISTILLATION: Hybrid-CNN-3Layer vs 4-Layer-Standard")
print("="*110)
print(f"{'Run':<35} {'Alpha':>6} {'Temp':>6} {'Accuracy':>10} {'F1':>8} {'Params':>10} {'Compress':>10} {'Time':>8}")
print("-"*110)
print(f"{'Teacher (DNABERT-2)':<35} {'--':>6} {'--':>6} {TEACHER_ACCURACY:>9.2%} {'--':>8} {teacher_params/1e6:>8.1f}M {'1.0x':>10} {'--':>8}")
print("-"*110)

for key, res in sorted(final_results.items()):
    print(f"{key:<35} {res['alpha']:>6.1f} {res['temperature']:>6.1f} {res['accuracy']:>9.2%} {res['f1']:>8.4f} {res['params']/1e6:>8.1f}M {res['compression']:>9.1f}x {res['train_time_min']:>6.1f}m")
print("="*110)

# ===== HEAD-TO-HEAD COMPARISON =====
configs = [(0.3, 1.0), (0.3, 3.0), (0.3, 5.0), (0.5, 1.0)]
arch_names = ["Hybrid-CNN-3Layer", "4-Layer-Standard"]

print(f"\n{'='*80}")
print("HEAD-TO-HEAD: Same (alpha, temp) — Hybrid vs 4-Layer Transformer")
print(f"{'='*80}")
print(f"{'Alpha':>6} {'Temp':>6} {'Hybrid Acc':>12} {'4L-Trans Acc':>14} {'Winner':>20}")
print("-"*80)

for alpha, temp in configs:
    h_key = f"Hybrid-CNN-3Layer_a{alpha}_t{temp}"
    t_key = f"4-Layer-Standard_a{alpha}_t{temp}"
    h_acc = final_results.get(h_key, {}).get("accuracy", 0)
    t_acc = final_results.get(t_key, {}).get("accuracy", 0)
    diff = h_acc - t_acc
    winner = "Hybrid" if diff > 0 else "4L-Transformer" if diff < 0 else "Tie"
    print(f"{alpha:>6.1f} {temp:>6.1f} {h_acc:>11.2%} {t_acc:>13.2%} {winner:>15} ({abs(diff):.2%})")
print("="*80)

# ===== BEST CONFIG PER ARCHITECTURE =====
print(f"\n{'='*70}")
print("BEST CONFIGURATION PER ARCHITECTURE")
print(f"{'='*70}")
for arch in arch_names:
    arch_results = {k: v for k, v in final_results.items() if v["architecture"] == arch}
    if not arch_results:
        continue
    best_key = max(arch_results, key=lambda k: arch_results[k]["accuracy"])
    best = arch_results[best_key]
    retention = best["accuracy"] / TEACHER_ACCURACY * 100
    print(f"\n  {arch}:")
    print(f"    Best config: alpha={best['alpha']}, temp={best['temperature']}")
    print(f"    Accuracy: {best['accuracy']:.2%} ({retention:.1f}% of teacher)")
    print(f"    F1: {best['f1']:.4f}")
    print(f"    Compression: {best['compression']:.1f}x")

# ===== GROUPED BAR CHART: Side-by-side comparison =====
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

config_labels = [f"a={a},T={t}" for a, t in configs]
hybrid_accs = [final_results.get(f"Hybrid-CNN-3Layer_a{a}_t{t}", {}).get("accuracy", 0) for a, t in configs]
trans_accs = [final_results.get(f"4-Layer-Standard_a{a}_t{t}", {}).get("accuracy", 0) for a, t in configs]

x = np.arange(len(configs))
width = 0.35

# 1. Accuracy comparison (grouped bars)
bars1 = axes[0].bar(x - width/2, hybrid_accs, width, label="Hybrid-CNN-3Layer", color="#2ecc71")
bars2 = axes[0].bar(x + width/2, trans_accs, width, label="4-Layer-Standard", color="#3498db")
axes[0].axhline(y=TEACHER_ACCURACY, color="gold", linestyle="--", linewidth=2, label=f"Teacher ({TEACHER_ACCURACY:.2%})")
axes[0].set_ylabel("Accuracy")
axes[0].set_title("Accuracy by (Alpha, Temp) Config")
axes[0].set_xticks(x)
axes[0].set_xticklabels(config_labels, rotation=15)
axes[0].legend(fontsize=8)
axes[0].set_ylim(0.88, 0.97)
for bar in bars1:
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001, f"{bar.get_height():.2%}", ha="center", fontsize=7)
for bar in bars2:
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001, f"{bar.get_height():.2%}", ha="center", fontsize=7)

# 2. Model size comparison
best_per_arch = {}
for arch in arch_names:
    arch_results = {k: v for k, v in final_results.items() if v["architecture"] == arch}
    if arch_results:
        best_key = max(arch_results, key=lambda k: arch_results[k]["accuracy"])
        best_per_arch[arch] = arch_results[best_key]

bar_names = ["Teacher"] + list(best_per_arch.keys())
bar_params = [teacher_params / 1e6] + [best_per_arch[n]["params"] / 1e6 for n in best_per_arch]
bar_colors = ["gold", "#2ecc71", "#3498db"]
bars3 = axes[1].bar(bar_names, bar_params, color=bar_colors[:len(bar_names)])
axes[1].set_ylabel("Parameters (M)")
axes[1].set_title("Model Size Comparison")
for bar, p in zip(bars3, bar_params):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, f"{p:.1f}M", ha="center", fontsize=9)

# 3. Best accuracy per architecture
best_names = list(best_per_arch.keys())
best_accs = [best_per_arch[n]["accuracy"] for n in best_names]
bars4 = axes[2].bar(best_names, best_accs, color=["#2ecc71", "#3498db"][:len(best_names)])
axes[2].axhline(y=TEACHER_ACCURACY, color="gold", linestyle="--", linewidth=2, label=f"Teacher ({TEACHER_ACCURACY:.2%})")
axes[2].set_ylabel("Accuracy")
axes[2].set_title("Best Accuracy per Architecture")
axes[2].legend()
axes[2].set_ylim(0.88, 0.97)
for bar, acc in zip(bars4, best_accs):
    axes[2].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002, f"{acc:.2%}", ha="center", fontsize=9)

plt.tight_layout()
plt.savefig("/kaggle/working/distillation_comparison.png", dpi=150, bbox_inches="tight")
plt.show()
print("Charts saved to /kaggle/working/distillation_comparison.png")

# ===== SAVE RESULTS JSON =====
results_json = {
    "teacher_accuracy": TEACHER_ACCURACY,
    "teacher_params": teacher_params,
    "configs_tested": [{"alpha": a, "temperature": t} for a, t in configs],
    "runs": final_results,
}
with open("/kaggle/working/distillation_results.json", "w") as f:
    json.dump(results_json, f, indent=2)
print("Results saved to /kaggle/working/distillation_results.json")